=== TcMenu/tcMenu/xmlPlugins/tcmenu-plugin-item.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema"
           targetNamespace="https://www.thecoderscorner.com/libraries/tcmenuPluginItem"
           xmlns="https://www.thecoderscorner.com/libraries/tcmenuPluginItem">
  <xs:element name="TcMenuPlugin" type="TcMenuPluginType"/>
  <xs:complexType name="SupportedPlatformsType">
    <xs:sequence>
      <xs:element name="Platform" maxOccurs="unbounded" minOccurs="0">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:enumeration value="ARDUINO_UNO"/>
            <xs:enumeration value="ARDUINO_AVR"/>
            <xs:enumeration value="ARDUINO_32"/>
            <xs:enumeration value="ARDUINO_ESP8266"/>
            <xs:enumeration value="ARDUINO_ESP32"/>
            <xs:enumeration value="STM32DUINO"/>
            <xs:enumeration value="RASPBERRY_PIJ"/>
            <xs:enumeration value="MBED_RTOS"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="DocumentationType">
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute type="xs:string" name="link"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
  <xs:complexType name="RequiredLibrariesType">
    <xs:sequence>
      <xs:element name="Library" type="xs:string" maxOccurs="unbounded" minOccurs="0">
      </xs:element>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="PropertyType" mixed="true">
    <xs:sequence>
      <xs:element type="ChoicesType" name="Choices" minOccurs="0"/>
    </xs:sequence>
    <xs:attribute type="xs:string" name="id" use="required"/>
    <xs:attribute type="xs:string" name="name" use="required"/>
    <xs:attribute type="xs:string" name="initial" use="required"/>
    <xs:attribute type="xs:string" name="desc" use="required"/>
    <xs:attribute type="xs:string" name="type" use="required"/>
    <xs:attribute type="xs:string" name="min"/>
    <xs:attribute type="xs:string" name="max"/>
    <xs:attribute type="xs:string" name="matches"/>
    <xs:attribute type="xs:string" name="whenProperty"/>
    <xs:attribute type="xs:string" name="isValue"/>
    <xs:attribute type="xs:string" name="isNotValue"/>
  </xs:complexType>
  <xs:complexType name="ChoiceType">
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute name="desc" type="xs:string"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
  <xs:complexType name="ChoicesType">
    <xs:sequence>
      <xs:element name="Choice" type="ChoiceType" maxOccurs="unbounded" minOccurs="0"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="PropertiesType">
    <xs:sequence>
      <xs:element type="PropertyType" name="Property" maxOccurs="unbounded" minOccurs="0"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="ReplacementType">
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute type="xs:string" name="find" use="required"/>
        <xs:attribute type="xs:string" name="replace" use="required"/>
        <xs:attribute type="xs:string" name="whenProperty"/>
        <xs:attribute type="xs:string" name="matches"/>
        <xs:attribute type="xs:string" name="isValue"/>
        <xs:attribute type="xs:string" name="isNotValue"/>
        <xs:attribute type="xs:string" name="applicabilityRef"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
  <xs:complexType name="SourceFileType" mixed="true">
    <xs:attribute type="xs:string" name="name" use="required"/>
    <xs:attribute type="xs:string" name="matches"/>
    <xs:attribute type="xs:string" name="whenProperty"/>
    <xs:attribute type="xs:string" name="isValue"/>
    <xs:attribute type="xs:string" name="isNotValue"/>
    <xs:attribute type="xs:string" name="applicabilityRef"/>
    <xs:attribute type="xs:string" name="overwrite"/>
  </xs:complexType>
  <xs:complexType name="SourceFilesType">
    <xs:sequence>
      <xs:element type="ReplacementType" name="Replacement" maxOccurs="unbounded" minOccurs="0"/>
      <xs:element type="SourceFileType" name="SourceFile" maxOccurs="unbounded" minOccurs="0"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="HeaderType">
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute type="xs:string" name="name" use="required"/>
        <xs:attribute type="xs:string" name="inSource" use="required"/>
        <xs:attribute type="xs:string" name="priority"/>
        <xs:attribute type="xs:string" name="matches"/>
        <xs:attribute type="xs:string" name="whenProperty"/>
        <xs:attribute type="xs:string" name="isValue"/>
        <xs:attribute type="xs:string" name="isNotValue"/>
        <xs:attribute type="xs:string" name="applicabilityRef"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
  <xs:complexType name="IncludeFilesType">
    <xs:sequence>
      <xs:element type="HeaderType" name="Header" maxOccurs="unbounded" minOccurs="0" />
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="ApplicabilityType">
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute type="xs:string" name="matches"/>
        <xs:attribute type="xs:string" name="whenProperty"/>
        <xs:attribute type="xs:string" name="isValue"/>
        <xs:attribute type="xs:string" name="isNotValue"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
  <xs:complexType name="ApplicabilityDefType">
    <xs:sequence>
      <xs:element type="ApplicabilityType" name="Applicability" maxOccurs="unbounded" minOccurs="0" />
      <xs:element type="ApplicabilityDefType" name="ApplicabilityDef" minOccurs="0"/>
    </xs:sequence>
    <xs:attribute type="xs:string" name="mode"/>
    <xs:attribute type="xs:string" name="key"/>
  </xs:complexType>
  <xs:complexType name="ApplicabilityDefsType">
    <xs:sequence>
      <xs:element type="ApplicabilityDefType" name="ApplicabilityDef" maxOccurs="unbounded" minOccurs="0"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="ParamType">
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute type="xs:string" name="value"/>
        <xs:attribute type="xs:string" name="default"/>
        <xs:attribute type="xs:string" name="type"/>
        <xs:attribute type="xs:string" name="name"/>
        <xs:attribute type="xs:string" name="used"/>
        <xs:attribute type="xs:string" name="ref"/>
        <xs:attribute type="xs:string" name="font"/>
        <xs:attribute type="xs:string" name="ioDevice"/>
        <xs:attribute type="xs:string" name="lambda"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
  <xs:complexType name="VariableType" mixed="true">
    <xs:sequence>
      <xs:element type="ParamType" name="Param" minOccurs="0" maxOccurs="unbounded"/>
    </xs:sequence>
    <xs:attribute type="xs:string" name="name"/>
    <xs:attribute type="xs:string" name="type"/>
    <xs:attribute type="xs:string" name="export"/>
    <xs:attribute type="xs:string" name="progmem"/>
    <xs:attribute type="xs:string" name="matches"/>
    <xs:attribute type="xs:string" name="whenProperty"/>
    <xs:attribute type="xs:string" name="isValue"/>
    <xs:attribute type="xs:string" name="isNotValue"/>
    <xs:attribute type="xs:string" name="applicabilityRef"/>
  </xs:complexType>
  <xs:complexType name="GlobalVariablesType">
    <xs:sequence>
      <xs:element type="VariableType" name="Variable" maxOccurs="unbounded" minOccurs="0"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="FunctionType">
    <xs:sequence>
      <xs:element type="ParamType" name="Param" maxOccurs="unbounded" minOccurs="0"/>
    </xs:sequence>
    <xs:attribute type="xs:string" name="name"/>
    <xs:attribute type="xs:string" name="object"/>
    <xs:attribute type="xs:string" name="matches"/>
    <xs:attribute type="xs:string" name="whenProperty"/>
    <xs:attribute type="xs:string" name="isValue"/>
    <xs:attribute type="xs:string" name="isNotValue"/>
    <xs:attribute type="xs:string" name="applicabilityRef"/>
    <xs:attribute type="xs:string" name="pointer"/>
  </xs:complexType>
  <xs:complexType name="LambdaType">
    <xs:sequence>
      <xs:element type="ParamType" name="Param" maxOccurs="unbounded" minOccurs="0"/>
      <xs:element type="FunctionType" name="Function" minOccurs="0" maxOccurs="unbounded"/>
    </xs:sequence>
    <xs:attribute type="xs:string" name="name"/>
    <xs:attribute type="xs:string" name="object"/>
    <xs:attribute type="xs:string" name="matches"/>
    <xs:attribute type="xs:string" name="whenProperty"/>
    <xs:attribute type="xs:string" name="isValue"/>
    <xs:attribute type="xs:string" name="isNotValue"/>
    <xs:attribute type="xs:string" name="applicabilityRef"/>
  </xs:complexType>
  <xs:complexType name="SetupFunctionsType">
    <xs:choice maxOccurs="unbounded" minOccurs="0">
      <xs:element type="FunctionType" name="Function" maxOccurs="unbounded" minOccurs="0"/>
      <xs:element type="LambdaType" name="Lambda"/>
    </xs:choice>
  </xs:complexType>
  <xs:complexType name="TcMenuPluginType">
    <xs:sequence>
      <xs:element type="SupportedPlatformsType" name="SupportedPlatforms"/>
      <xs:element type="xs:string" name="Description"/>
      <xs:element type="DocumentationType" name="Documentation"/>
      <xs:element type="RequiredLibrariesType" name="RequiredLibraries"/>
      <xs:element type="xs:string" name="ImageFile"/>
      <xs:element type="PropertiesType" name="Properties"/>
      <xs:element type="ApplicabilityDefsType" name="ApplicabilityDefs"/>
      <xs:element type="SourceFilesType" name="SourceFiles"/>
      <xs:element type="IncludeFilesType" name="IncludeFiles"/>
      <xs:element type="GlobalVariablesType" name="GlobalVariables"/>
      <xs:element type="SetupFunctionsType" name="SetupFunctions"/>
    </xs:sequence>
    <xs:attribute type="xs:string" name="name"/>
    <xs:attribute type="xs:string" name="id"/>
    <xs:attribute type="xs:string" name="subsystem"/>
    <xs:attribute type="xs:string" name="requiresDesigner"/>
    <xs:attribute type="xs:string" name="needsTheme"/>
  </xs:complexType>
</xs:schema>

=== TcMenu/tcMenu/xmlPlugins/core-remote/menuInMenuSerial.xml
<TcMenuPlugin name="Menu In Menu connection over Serial Connection" id="9BF2314D-ADCD-43D8-81A6-111F8C3AC5B8" subsystem="REMOTE"
              requiresDesigner="2.2.0" xmlns="https://www.thecoderscorner.com/libraries/tcmenuPluginItem" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
              xsi:schemaLocation="https://www.thecoderscorner.com/libraries/tcmenuPluginItem https://www.thecoderscorner.com/libraries/tcmenu-plugin-item.xsd">
    <SupportedPlatforms>
        <Platform>RASPBERRY_PIJ</Platform>
    </SupportedPlatforms>
    <Description>Use this option to create a serial connection from another device to your embedded Java application on Raspberry PI/embedded Linux. The menu is nested under an existing submenu.</Description>
    <Documentation link="https://www.thecoderscorner.com/products/arduino-libraries/tc-menu/tcmenu-iot/java-menu-in-menu/"/>
    <RequiredLibraries/>
    <ImageFile>menu-in-menu.png</ImageFile>

    <Properties>
        <Property id="ETH_CONCURRENT_CONNECTIONS" name="Number of concurrent connections" desc="The number of concurrent connects to allow, each uses memory" initial="1" type="choice">
            <Choices>
                <Choice desc="One remote at a time">1</Choice>
                <Choice desc="Up to two remotes at once">2</Choice>
                <Choice desc="Up to three remotes at once">3</Choice>
            </Choices>
        </Property>
        <Property id="ETH_LIBRARY_TYPE" name="Ethernet library type" desc="Choose the library that supports your hardware" initial="ETHERNET_2" type="choice">
            <Choices>
                <Choice desc="Ethernet 2">ETHERNET_2</Choice>
                <Choice desc="UIP Ethernet">UIP_ENC28J60</Choice>
                <Choice desc="STM32Ethernet">STM32ETHERNET</Choice>
            </Choices>
        </Property>
        <Property id="ETH_LISTEN_PORT1" name="First port on which to listen " initial="3333" desc="The first port on which to listen for connections"
                  type="int" min="0" max="65535"/>
        <Property id="ETH_LISTEN_PORT2" name="Second port on which to listen" initial="3334" desc="The second port on which to listen for connections"
                  type="int" min="0" max="65535" whenProperty="ETH_CONCURRENT_CONNECTIONS" matches="[23]"/>
        <Property id="ETH_LISTEN_PORT3" name="Third port on which to listen" initial="3335" desc="The third port on which to listen for connections"
                  type="int" min="0" max="65535"  whenProperty="ETH_CONCURRENT_CONNECTIONS" isValue="3"/>
    </Properties>

    <ApplicabilityDefs/>

    <SourceFiles>
        <Replacement find="Ethernet.h" replace="STM32Ethernet.h" whenProperty="ETH_LIBRARY_TYPE" isValue="STM32ETHERNET"/>
        <Replacement find="Ethernet.h" replace="UIPEthernet.h" whenProperty="ETH_LIBRARY_TYPE" isValue="UIP_ENC28J60"/>
        <Replacement find="EthernetClient" replace="UIPClient" whenProperty="ETH_LIBRARY_TYPE" isValue="UIP_ENC28J60"/>
        <Replacement find="EthernetServer" replace="UIPServer" whenProperty="ETH_LIBRARY_TYPE" isValue="UIP_ENC28J60"/>
        <Replacement find="ETHERNET_BUFFER_SIZE 0" replace="ETHERNET_BUFFER_SIZE 64" whenProperty="ETH_LIBRARY_TYPE" isValue="ETHERNET_2"/>

        <SourceFile name="ethernetSrc/EthernetTransport.cpp"/>
        <SourceFile name="ethernetSrc/EthernetTransport.h"/>
    </SourceFiles>

    <IncludeFiles>
        <Header name="EthernetTransport.h" inSource="true"/>
        <Header name="RemoteConnector.h" inSource="false"/>
    </IncludeFiles>

    <GlobalVariables>
        <Variable name="server" type="EthernetServer" export="true">
            <Param value="${ETH_LISTEN_PORT1}" default="3333" />
        </Variable>
        <Variable name="ethernetInitialisation" type="EthernetInitialisation" export="true">
            <Param ref="server"/>
        </Variable>
        <Variable name="ethernetTransport" type="EthernetTagValTransport" export="false"/>
        <Variable name="ethernetConnection" type="TagValueRemoteServerConnection" export="false">
            <Param value="ethernetTransport"/>
            <Param value="ethernetInitialisation"/>
        </Variable>

        <Variable name="server2" type="EthernetServer" export="true"  whenProperty="ETH_CONCURRENT_CONNECTIONS" matches="[23]">
            <Param value="${ETH_LISTEN_PORT2}" default="3334" />
        </Variable>
        <Variable name="ethernetInitialisation2" type="EthernetInitialisation" export="true"  whenProperty="ETH_CONCURRENT_CONNECTIONS" matches="[23]">
            <Param ref="server2"/>
        </Variable>
        <Variable name="ethernetTransport2" type="EthernetTagValTransport" export="false"  whenProperty="ETH_CONCURRENT_CONNECTIONS" matches="[23]"/>
        <Variable name="ethernetConnection2" type="TagValueRemoteServerConnection" export="false"  whenProperty="ETH_CONCURRENT_CONNECTIONS" matches="[23]">
            <Param value="ethernetTransport2"/>
            <Param value="ethernetInitialisation2"/>
        </Variable>

        <Variable name="server3" type="EthernetServer" export="true" whenProperty="ETH_CONCURRENT_CONNECTIONS" isValue="3">
            <Param value="${ETH_LISTEN_PORT3}" default="3335" />
        </Variable>
        <Variable name="ethernetInitialisation3" type="EthernetInitialisation" export="true" whenProperty="ETH_CONCURRENT_CONNECTIONS" isValue="3">
            <Param ref="server3"/>
        </Variable>
        <Variable name="ethernetTransport3" type="EthernetTagValTransport" export="false"  whenProperty="ETH_CONCURRENT_CONNECTIONS" isValue="3"/>
        <Variable name="ethernetConnection3" type="TagValueRemoteServerConnection" export="false"  whenProperty="ETH_CONCURRENT_CONNECTIONS" isValue="3">
            <Param value="ethernetTransport3"/>
            <Param value="ethernetInitialisation3"/>
        </Variable>
    </GlobalVariables>

    <SetupFunctions>
        <Function name="addConnection" object="remoteServer">
            <Param ref="ethernetConnection"/>
        </Function>

        <Function name="addConnection" object="remoteServer" whenProperty="ETH_CONCURRENT_CONNECTIONS" matches="[23]">
            <Param ref="ethernetConnection2"/>
        </Function>

        <Function name="addConnection" object="remoteServer" whenProperty="ETH_CONCURRENT_CONNECTIONS" isValue="3">
            <Param ref="ethernetConnection3"/>
        </Function>
    </SetupFunctions>
</TcMenuPlugin>

=== TcMenu/tcMenu/xmlPlugins/core-remote/noRemote.xml
<TcMenuPlugin name="No remote capabilities" id="2c101fec-1f7d-4ff3-8d2b-992ad41e7fcb" subsystem="REMOTE"
              xmlns="https://www.thecoderscorner.com/libraries/tcmenuPluginItem" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
              xsi:schemaLocation="https://www.thecoderscorner.com/libraries/tcmenuPluginItem https://www.thecoderscorner.com/libraries/tcmenu-plugin-item.xsd">
    <SupportedPlatforms>
        <Platform>ARDUINO_UNO</Platform>
        <Platform>ARDUINO_AVR</Platform>
        <Platform>ARDUINO_32</Platform>
        <Platform>ARDUINO_ESP8266</Platform>
        <Platform>ARDUINO_ESP32</Platform>
        <Platform>STM32DUINO</Platform>
        <Platform>RASPBERRY_PIJ</Platform>
        <Platform>MBED_RTOS</Platform>
    </SupportedPlatforms>
    <Description>Select this option when you don't need any remote control functionality.</Description>
    <Documentation link="https://www.thecoderscorner.com/products/arduino-libraries/tc-menu/menu-library-remote-connectivity/"/>
    <RequiredLibraries/>
    <ImageFile>no-display.png</ImageFile>

    <Properties/>

    <ApplicabilityDefs/>

    <SourceFiles/>

    <IncludeFiles/>

    <GlobalVariables/>

    <SetupFunctions/>
</TcMenuPlugin>

=== TcMenu/tcMenu/xmlPlugins/core-display/analogJoystickInput.xml
<TcMenuPlugin name="Control menu with analog joystick"
              id="20409bb8-b8a1-4d1d-b632-2cf9b57353e3" subsystem="INPUT"
              requiresDesigner="2.2"
              xmlns="https://www.thecoderscorner.com/libraries/tcmenuPluginItem" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
              xsi:schemaLocation="https://www.thecoderscorner.com/libraries/tcmenuPluginItem https://www.thecoderscorner.com/libraries/tcmenu-plugin-item.xsd">
<SupportedPlatforms>
       <Platform>ARDUINO_UNO</Platform>
       <Platform>ARDUINO_AVR</Platform>
       <Platform>ARDUINO_32</Platform>
       <Platform>STM32DUINO</Platform>
       <Platform>ARDUINO_ESP8266</Platform>
       <Platform>ARDUINO_ESP32</Platform>
       <Platform>MBED_RTOS</Platform>
</SupportedPlatforms>
    <Description>Use an analog joystick connected to one of the Arduino inbuilt analog pins along with a switch also connected to an Arduino pin.</Description>
    <Documentation link="https://www.thecoderscorner.com/products/arduino-libraries/tc-menu/tcmenu-plugins/encoder-switches-input-plugin/"/>
    <RequiredLibraries/>
    <ImageFile>joystick.jpg</ImageFile>

    <Properties>
        <Property id="SW_POLLING_MODE" name="Polling / Interrupt mode" initial="SWITCHES_POLL_EVERYTHING" desc="Choose how switches should poll / use interrupts" type="choice">
            <Choices>
                <Choice desc="Polling for keys and encoders">SWITCHES_POLL_EVERYTHING</Choice>
                <Choice desc="Everything interrupt driven">SWITCHES_NO_POLLING</Choice>
                <Choice desc="Keys polling, encoder A pin interrupt">SWITCHES_POLL_KEYS_ONLY</Choice>
            </Choices>
        </Property>
        <Property id="SWITCH_IODEVICE" name="IoAbstractionRef for Switches" initial="devicePins" desc="Advanced: IoAbstractionRef (default is Arduino pins)" type="io-device"/>
        <Property id="JOYSTICK_PIN" name="Analog Pin" initial="A0" desc="The analog pin the joystick is connected" type="pin"/>
        <Property id="BUTTON_PIN" name="Button Pin" initial="3" desc="The pin on which the button is connected" type="pin"/>
        <Property id="PULLUP_LOGIC" name="PullUp Logic" initial="true" desc="Enable this to use pull up logic, otherwise pull down" type="boolean"/>
    </Properties>

    <ApplicabilityDefs/>

    <SourceFiles/>

    <IncludeFiles>
        <Header name="JoystickSwitchInput.h" inSource="false"/>
    </IncludeFiles>

    <GlobalVariables>
        <Variable name="analogDevice" type="ArduinoAnalogDevice" export="true" whenProperty="TARGET" isNotValue="MBED_RTOS"/>
        <Variable name="analogDevice" type="MBedAnalogDevice" export="true" whenProperty="TARGET" isValue="MBED_RTOS"/>
    </GlobalVariables>

    <SetupFunctions>
        <Function name="init" object="switches">
            <Param ioDevice="${SWITCH_IODEVICE}" />
            <Param value="${SW_POLLING_MODE}" />
            <Param value="${PULLUP_LOGIC}"/>
        </Function>

        <Lambda name="onReleaseFn">
            <Param type="pinid_t" name="/*key*/"/>
            <Param type="bool" name="held"/>
            <Function name="onMenuSelect" object="menuMgr">
                <Param value="held"/>
            </Function>
        </Lambda>
        <Function name="addSwitch" object="switches">
            <Param value="${BUTTON_PIN}"/>
            <Param ref="NULL"/>
        </Function>
        <Function name="onRelease" object="switches">
            <Param value="${BUTTON_PIN}"/>
            <Param lambda="onReleaseFn"/>
        </Function>

        <Lambda name="analogReadFn">
            <Param type="int" name="val"/>
            <Function name="valueChanged" object="menuMgr">
                <Param value="val"/>
            </Function>
        </Lambda>
        <Function name="setupAnalogJoystickEncoder">
            <Param ref="analogDevice"/>
            <Param value="${JOYSTICK_PIN}"/>
            <Param lambda="analogReadFn"/>
        </Function>

        <Function name="initWithoutInput" object="menuMgr">
            <Param ref="renderer"/>
            <Param ref="${ROOT}"/>
        </Function>
    </SetupFunctions>
</TcMenuPlugin>

=== TcMenu/tcMenu/xmlPlugins/core-display/tftSpiDisplay.xml
<TcMenuPlugin name="TFT_eSPI display driver for color displays"
              id="e6342680-6fab-4d1b-ac08-ce8dbfc0974c" subsystem="DISPLAY"
              requiresDesigner="2.0" needsTheme="true"
              xmlns="https://www.thecoderscorner.com/libraries/tcmenuPluginItem" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
              xsi:schemaLocation="https://www.thecoderscorner.com/libraries/tcmenuPluginItem https://www.thecoderscorner.com/products/arduino-libraries/libraries/tcmenu-plugin-item.xsd">
    <SupportedPlatforms>
        <Platform>ARDUINO_32</Platform>
        <Platform>ARDUINO_ESP8266</Platform>
        <Platform>ARDUINO_ESP32</Platform>
        <Platform>STM32DUINO</Platform>
    </SupportedPlatforms>
    <Description>Draw menus using the TFT_eSPI library with any configuration that you have for color TFTs. Supports double buffering and all menu display types. Can use the library touch functions.</Description>
    <Documentation link="https://www.thecoderscorner.com/products/arduino-libraries/tc-menu/tcmenu-plugins/tft_espi-renderer-plugin/"/>
    <RequiredLibraries/>
    <ImageFile>adagfx-color.jpg</ImageFile>
    <Properties>
        <Property id="DISPLAY_VARIABLE" name="%core.display.variable" initial="gfx" desc="%core.display.variable.auto.desc" type="variable" />
        <Property id="DISPLAY_ROTATION" name="%adafruit.display.rotation" initial="2" desc="%adafruit.display.rotation.desc" type="int" min="0" max="3" />
        <Property id="DOUBLE_BUFFER_ROWS" name="%core.display.buffer.size" initial="0" desc="%core.display.buffer.size.desc" type="int" min="0" max="250" />
        <Property id="UPDATES_PER_SEC" name="%core.screen.updates.sec" initial="10" desc="core.screen.updates.sec.desc" type="int" min="1" max="30" />

        <Property id="TOUCH_SEPARATOR" name="%core.touch.separator" initial="" desc="%core.touch.separator.desc" type="separator"/>
        <Property id="TFT_TOUCH_SCREEN_REQUIRED" name="%core.touch.required" initial="false" desc="%core.touch.required.desc" type="boolean" />
        <Property id="TOUCH_CALIB_WIDTH" name="%touch.tft.calib.width" type="int" min="1" max="65535" initial="240"
                  desc="%touch.tft.calib.width.desc" whenProperty="TFT_TOUCH_SCREEN_REQUIRED" isValue="true"/>
        <Property id="TOUCH_CALIB_HEIGHT" name="%touch.tft.calib.height" type="int" min="1" max="65535" initial="320"
                  desc="%touch.tft.calib.height.desc" whenProperty="TFT_TOUCH_SCREEN_REQUIRED" isValue="true"/>
        <Property id="TOUCH_USE_RAW_TFT_FUNCTION" name="%touch.tft.use.raw" initial="true" type="boolean"
                  desc="%touch.tft.use.raw.desc" whenProperty="TFT_TOUCH_SCREEN_REQUIRED" isValue="true" />

        <Property id="ORIENTATION_SEPARATOR" name="%core.touch.orientation" initial="" desc="%core.touch.orientation.desc" type="separator"/>
        <Property id="TFT_TOUCH_SWAP_XY" name="%core.touch.swap.xy" initial="false" whenProperty="TOUCH_SCREEN_REQUIRED" isValue="true"
                  desc="%core.touch.swap.xy.desc" type="boolean" />
        <Property id="TFT_TOUCH_X_INVERTED" name="%core.touch.x.inverted" initial="false" whenProperty="TOUCH_SCREEN_REQUIRED" isValue="true"
                  type="boolean" desc="%core.touch.x.inverted.desc"/>
        <Property id="TFT_TOUCH_Y_INVERTED" name="%core.touch.y.inverted" initial="false" whenProperty="TOUCH_SCREEN_REQUIRED" isValue="true"
                  type="boolean" desc="%core.touch.y.inverted.desc"/>

        <Property id="CALIB_SEPARATOR" name="%core.touch.calibration" initial="" desc="%core.touch.calibration.desc" type="separator"/>
        <Property id="TFT_TOUCH_SCREEN_CALIBRATE" name="%core.enable.touch.calib" initial="true"
                  desc="%core.enable.touch.calib.desc" type="boolean" whenProperty="TOUCH_SCREEN_REQUIRED" isValue="true"  />
        <Property id="TFT_TOUCH_CALIBRATION_STORAGE_LOC" name="%core.touch.calib.addr" initial="400" type="int"
                  desc="%core.touch.calib.addr.desc"  min="4" max="65535" whenProperty="TOUCH_SCREEN_REQUIRED" isValue="true" />
    </Properties>

    <ApplicabilityDefs>
        <ApplicabilityDef key="touchCalibrationNeeded" mode="and">
            <Applicability whenProperty="TFT_TOUCH_SCREEN_REQUIRED" isValue="true"/>
            <Applicability whenProperty="TFT_TOUCH_SCREEN_CALIBRATE" isValue="true"/>
        </ApplicabilityDef>
    </ApplicabilityDefs>

    <SourceFiles>
        <Replacement find="define TC_TFT_ESPI_NEEDS_TOUCH (true|false)" replace="define TC_TFT_ESPI_NEEDS_TOUCH ${TFT_TOUCH_SCREEN_REQUIRED}"/>
        <SourceFile name="tfteSpi/tcMenuTfteSpi.cpp"/>
        <SourceFile name="tfteSpi/tcMenuTfteSpi.h"/>
    </SourceFiles>

    <IncludeFiles>
        <Header name="tcMenuTfteSpi.h" inSource="true"/>
        <Header name="graphics/MenuTouchScreenEncoder.h" inSource="false" whenProperty="TFT_TOUCH_SCREEN_REQUIRED" isValue="true"/>
        <Header name="extras/DrawableTouchCalibrator.h" inSource="false" applicabilityRef="touchCalibrationNeeded"/>
    </IncludeFiles>

    <GlobalVariables>
        <Variable name="${DISPLAY_VARIABLE}" type="TFT_eSPI" export="true" />

        <Variable name="${DISPLAY_VARIABLE}Drawable" type="TfteSpiDrawable" export="true">
            <Param ref="${DISPLAY_VARIABLE}"/>
            <Param value="${DOUBLE_BUFFER_ROWS}"/>
        </Variable>

        <Variable name="renderer" type="GraphicsDeviceRenderer" export="true">
            <Param value="30"/>
            <Param value="applicationInfo.name"/>
            <Param ref="${DISPLAY_VARIABLE}Drawable"/>
        </Variable>

        <Variable name="touchInterrogator" type="iotouch::TftSpiTouchInterrogator" export="true" whenProperty="TFT_TOUCH_SCREEN_REQUIRED" isValue="true">
            <Param ref="${DISPLAY_VARIABLE}"/>
            <Param value="${TOUCH_CALIB_WIDTH}"/>
            <Param value="${TOUCH_CALIB_HEIGHT}"/>
            <Param value="${TOUCH_USE_RAW_TFT_FUNCTION}"/>
        </Variable>

        <Variable name="touchOrientation" type="iotouch::TouchOrientationSettings" export="false" whenProperty="TFT_TOUCH_SCREEN_REQUIRED" isValue="true">
            <Param value="${TFT_TOUCH_SWAP_XY}"/>
            <Param value="${TFT_TOUCH_X_INVERTED}"/>
            <Param value="${TFT_TOUCH_Y_INVERTED}"/>
        </Variable>

        <Variable name="touchScreen" type="MenuTouchScreenManager" export="true" whenProperty="TFT_TOUCH_SCREEN_REQUIRED" isValue="true">
            <Param ref="touchInterrogator"/>
            <Param ref="renderer"/>
            <Param value="touchOrientation"/>
        </Variable>

        <Variable name="touchCalibrator" type="tcextras::IoaTouchScreenCalibrator" export="true" applicabilityRef="touchCalibrationNeeded">
            <Param ref="touchScreen"/>
            <Param ref="renderer"/>
            <Param value="${TFT_TOUCH_CALIBRATION_STORAGE_LOC}"/>
        </Variable>
    </GlobalVariables>

    <SetupFunctions>
        <Function object="${DISPLAY_VARIABLE}" name="begin"/>

        <Function object="${DISPLAY_VARIABLE}" name="setRotation">
            <Param value="${DISPLAY_ROTATION}"/>
        </Function>

        <Function object="renderer" name="setUpdatesPerSecond">
            <Param value="${UPDATES_PER_SEC}"/>
        </Function>

        <Function name="start" object="touchScreen"  whenProperty="TFT_TOUCH_SCREEN_REQUIRED" isValue="true" />
    </SetupFunctions>
</TcMenuPlugin>
