=== TcMenu/tcMenu/xmlPlugins/tcmenu-plugin.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema"
           targetNamespace="https://www.thecoderscorner.com/libraries/tcmenuPlugin"
           xmlns="https://www.thecoderscorner.com/libraries/tcmenuPlugin">
  <xs:element name="TcMenuPluginDefinition" type="TcMenuPluginDefinitionType"/>
  <xs:complexType name="AuthorType">
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute type="xs:string" name="name"/>
        <xs:attribute type="xs:string" name="url"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
  <xs:complexType name="LicenseType">
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute type="xs:string" name="name"/>
        <xs:attribute type="xs:string" name="url"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
  <xs:complexType name="GeneralDetailsType">
    <xs:sequence>
      <xs:element type="AuthorType" name="Author"/>
      <xs:element type="xs:string" name="Version"/>
      <xs:element type="xs:string" name="Name"/>
      <xs:element type="xs:string" name="Description"/>
      <xs:element type="LicenseType" name="License"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="PluginsType">
    <xs:sequence>
      <xs:element name="Plugin" maxOccurs="unbounded" minOccurs="0" type="xs:string"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="TcMenuPluginDefinitionType">
    <xs:attribute name="shortName" type="xs:string" use="required"/>
    <xs:sequence>
      <xs:element type="GeneralDetailsType" name="GeneralDetails"/>
      <xs:element type="PluginsType" name="Plugins"/>
    </xs:sequence>
  </xs:complexType>
</xs:schema>

=== TcMenu/tcMenu/xmlPlugins/core-display/tcmenu-plugin.xml
<?xml version="1.0" ?>
<TcMenuPluginDefinition shortName="core-display" xmlns="https://www.thecoderscorner.com/libraries/tcmenuPlugin"
                        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                        xsi:schemaLocation="https://www.thecoderscorner.com/libraries/tcmenuPlugin https://tcmenu.github.io/documentation/arduino-libraries/libraries/tcmenu-plugin.xsd">
    <GeneralDetails>
        <Author name="The Coders Corner" url="http://www.thecoderscorner.com/" />
        <Version>9.99.99</Version>
        <Name>%plugin.name</Name>
        <Description>This plugin provides support for most basic inputs and most textual and graphical displays.</Description>
        <License name="Apache 2.0" url="http://www.apache.org/licenses/LICENSE-2.0"/>
    </GeneralDetails>

    <Plugins>
        <!-- df robot specific -->
        <Plugin>dfRobotJoystick.xml</Plugin>

        <!-- display plugins -->
        <Plugin>i2cLiquidCrystalDisplay.xml</Plugin>
        <Plugin>liquidCrystalDisplay.xml</Plugin>
        <Plugin>adaGfxDisplay.xml</Plugin>
        <Plugin>u8g2SimpleBuilder.xml</Plugin>
        <Plugin>u8g2Display.xml</Plugin>
        <Plugin>tftSpiDisplay.xml</Plugin>
        <Plugin>ssd1306asciiDisplayQuickStart.xml</Plugin>
        <Plugin>ssd1306asciiDisplay.xml</Plugin>

        <!-- input plugins-->
        <Plugin>rotaryEncoderInput.xml</Plugin>
        <Plugin>upDownSwitchesInput.xml</Plugin>
        <Plugin>oneButtonSwitchesInput.xml</Plugin>
        <Plugin>twoButtonSwitchesInput.xml</Plugin>
        <Plugin>analogJoystickInput.xml</Plugin>
        <Plugin>analogResistiveTouchScreen.xml</Plugin>
        <Plugin>ArduinoTouchLibraryIntegration.xml</Plugin>
        <Plugin>esp32TouchSensor.xml</Plugin>
        <Plugin>matrixKeyboard.xml</Plugin>

        <!-- True CPP (PicoSDK/Mbed) specific displays -->
        <Plugin>adaMbedOled.xml</Plugin>
        <Plugin>adafruitTrueCpp.xml</Plugin>
        <Plugin>stm32BspFrameBuffer.xml</Plugin>

        <!-- custom cases -->
        <Plugin>noInput.xml</Plugin>
        <Plugin>noDisplay.xml</Plugin>
        <Plugin>customDrawable.xml</Plugin>
        <Plugin>customDisplay.xml</Plugin>
    </Plugins>
</TcMenuPluginDefinition>

=== TcMenu/tcMenu/xmlPlugins/core-remote/tcmenu-plugin.xml
<?xml version="1.0" ?>
<TcMenuPluginDefinition shortName="core-remote" xmlns="https://www.thecoderscorner.com/libraries/tcmenuPlugin"
                        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                        xsi:schemaLocation="https://www.thecoderscorner.com/libraries/tcmenuPlugin https://tcmenu.github.io/documentation/arduino-libraries/libraries/tcmenu-plugin.xsd">
    <GeneralDetails>
        <Author name="The Coders Corner" url="http://www.thecoderscorner.com/" />
        <Version>9.99.99</Version>
        <Name>Core remote control</Name>
        <Description>This plugin contains remote control capabilites for Ethernet, WiFi, Bluetooth and Serial.</Description>
        <License name="Apache 2.0" url="http://www.apache.org/licenses/LICENSE-2.0"/>
    </GeneralDetails>

    <Plugins>
        <Plugin>noRemote.xml</Plugin>

        <!-- arduino remote plugins -->
        <Plugin>remoteSerial.xml</Plugin>
        <Plugin>remoteEthernet.xml</Plugin>

        <!-- esp specific -->
        <Plugin>remoteSerialESP.xml</Plugin>
        <Plugin>remoteWifiESP.xml</Plugin>

        <!-- client device -->
        <Plugin>clientRemoteEthernet.xml</Plugin>

        <!-- true cpp specific -->
        <Plugin>remoteMbedEthernet.xml</Plugin>
        <Plugin>remoteStdio.xml</Plugin>

        <!-- simhub connector -->
        <Plugin>simhubConnector.xml</Plugin>
    </Plugins>
</TcMenuPluginDefinition>

=== TcMenu/tcMenu/xmlPlugins/examples/example-plugin.xml
<?xml version="1.0" ?>
<TcMenuPluginDefinition shortName="demo-plugin" xmlns="https://www.thecoderscorner.com/libraries/tcmenuPlugin"
                        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                        xsi:schemaLocation="https://www.thecoderscorner.com/libraries/tcmenuPlugin https://www.thecoderscorner.com/libraries/tcmenu-plugin.xsd">
    <GeneralDetails>
        <Author name="The Coders Corner" url="http://www.thecoderscorner.com/" />
        <Version>1.3.5</Version>
        <Name>Demo plugin</Name>
        <Description>This plugin shows how to write plugins.</Description>
        <License name="Apache 2.0" url="http://www.apache.org/licenses/LICENSE-2.0"/>
    </GeneralDetails>

    <Plugins>
        <!-- each plugin item is listed below -->
        <Plugin>example-plugin-item.xml</Plugin>
    </Plugins>
</TcMenuPluginDefinition>

=== TcMenu/tcMenu/xmlPlugins/core-themes/tcmenu-plugin.xml
<?xml version="1.0" ?>
<TcMenuPluginDefinition shortName="core-themes" xmlns="https://www.thecoderscorner.com/libraries/tcmenuPlugin"
                        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                        xsi:schemaLocation="https://www.thecoderscorner.com/libraries/tcmenuPlugin https://tcmenu.github.io/documentation/arduino-libraries/libraries/tcmenu-plugin.xsd">
    <GeneralDetails>
        <Author name="The Coders Corner" url="http://www.thecoderscorner.com/" />
        <Version>9.99.99</Version>
        <Name>%plugin.name</Name>
        <Description>This plugin provides themes that can be used with all graphical displays.</Description>
        <License name="Apache 2.0" url="http://www.apache.org/licenses/LICENSE-2.0"/>
    </GeneralDetails>

    <Plugins>
        <!-- mono plugins based on builder -->
        <Plugin>MonoInverseTitleBuilder.xml</Plugin>
        <Plugin>MonoBorderedTitleBuilder.xml</Plugin>

        <!-- Blue hue plugins -->
        <Plugin>CoolBlueModernBuilder.xml</Plugin>
        <Plugin>CoolBlueTraditionalBuilder.xml</Plugin>

        <!-- dark mode plugin -->
        <Plugin>DarkModeModernBuilder.xml</Plugin>
        <Plugin>DarkModeTraditionalBuilder.xml</Plugin>

        <!-- Manual plugins -->
        <Plugin>ManualTheme.xml</Plugin>
        <Plugin>NoThemeSelected.xml</Plugin>

        <!-- legacy plugins to delete in 12 months -->
        <Plugin>MonoBorderedTitle.xml</Plugin>
        <Plugin>MonoInverseTitle.xml</Plugin>
        <Plugin>CoolBlueModern.xml</Plugin>
        <Plugin>DarkModeModern.xml</Plugin>
        <Plugin>CoolBlueTraditional.xml</Plugin>
        <Plugin>DarkModeTraditional.xml</Plugin>
    </Plugins>
</TcMenuPluginDefinition>
