=== TcMenu/tcMenu/xmlPlugins/tcmenu-plugin-item.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema"
           targetNamespace="https://www.thecoderscorner.com/libraries/tcmenuPluginItem"
           xmlns="https://www.thecoderscorner.com/libraries/tcmenuPluginItem">
  <xs:element name="TcMenuPlugin" type="TcMenuPluginType"/>
  <xs:complexType name="SupportedPlatformsType">
    <xs:sequence>
      <xs:element name="Platform" maxOccurs="unbounded" minOccurs="0">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:enumeration value="ARDUINO_UNO"/>
            <xs:enumeration value="ARDUINO_AVR"/>
            <xs:enumeration value="ARDUINO_32"/>
            <xs:enumeration value="ARDUINO_ESP8266"/>
            <xs:enumeration value="ARDUINO_ESP32"/>
            <xs:enumeration value="STM32DUINO"/>
            <xs:enumeration value="RASPBERRY_PIJ"/>
            <xs:enumeration value="MBED_RTOS"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="DocumentationType">
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute type="xs:string" name="link"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
  <xs:complexType name="RequiredLibrariesType">
    <xs:sequence>
      <xs:element name="Library" type="xs:string" maxOccurs="unbounded" minOccurs="0">
      </xs:element>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="PropertyType" mixed="true">
    <xs:sequence>
      <xs:element type="ChoicesType" name="Choices" minOccurs="0"/>
    </xs:sequence>
    <xs:attribute type="xs:string" name="id" use="required"/>
    <xs:attribute type="xs:string" name="name" use="required"/>
    <xs:attribute type="xs:string" name="initial" use="required"/>
    <xs:attribute type="xs:string" name="desc" use="required"/>
    <xs:attribute type="xs:string" name="type" use="required"/>
    <xs:attribute type="xs:string" name="min"/>
    <xs:attribute type="xs:string" name="max"/>
    <xs:attribute type="xs:string" name="matches"/>
    <xs:attribute type="xs:string" name="whenProperty"/>
    <xs:attribute type="xs:string" name="isValue"/>
    <xs:attribute type="xs:string" name="isNotValue"/>
  </xs:complexType>
  <xs:complexType name="ChoiceType">
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute name="desc" type="xs:string"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
  <xs:complexType name="ChoicesType">
    <xs:sequence>
      <xs:element name="Choice" type="ChoiceType" maxOccurs="unbounded" minOccurs="0"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="PropertiesType">
    <xs:sequence>
      <xs:element type="PropertyType" name="Property" maxOccurs="unbounded" minOccurs="0"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="ReplacementType">
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute type="xs:string" name="find" use="required"/>
        <xs:attribute type="xs:string" name="replace" use="required"/>
        <xs:attribute type="xs:string" name="whenProperty"/>
        <xs:attribute type="xs:string" name="matches"/>
        <xs:attribute type="xs:string" name="isValue"/>
        <xs:attribute type="xs:string" name="isNotValue"/>
        <xs:attribute type="xs:string" name="applicabilityRef"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
  <xs:complexType name="SourceFileType" mixed="true">
    <xs:attribute type="xs:string" name="name" use="required"/>
    <xs:attribute type="xs:string" name="matches"/>
    <xs:attribute type="xs:string" name="whenProperty"/>
    <xs:attribute type="xs:string" name="isValue"/>
    <xs:attribute type="xs:string" name="isNotValue"/>
    <xs:attribute type="xs:string" name="applicabilityRef"/>
    <xs:attribute type="xs:string" name="overwrite"/>
  </xs:complexType>
  <xs:complexType name="SourceFilesType">
    <xs:sequence>
      <xs:element type="ReplacementType" name="Replacement" maxOccurs="unbounded" minOccurs="0"/>
      <xs:element type="SourceFileType" name="SourceFile" maxOccurs="unbounded" minOccurs="0"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="HeaderType">
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute type="xs:string" name="name" use="required"/>
        <xs:attribute type="xs:string" name="inSource" use="required"/>
        <xs:attribute type="xs:string" name="priority"/>
        <xs:attribute type="xs:string" name="matches"/>
        <xs:attribute type="xs:string" name="whenProperty"/>
        <xs:attribute type="xs:string" name="isValue"/>
        <xs:attribute type="xs:string" name="isNotValue"/>
        <xs:attribute type="xs:string" name="applicabilityRef"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
  <xs:complexType name="IncludeFilesType">
    <xs:sequence>
      <xs:element type="HeaderType" name="Header" maxOccurs="unbounded" minOccurs="0" />
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="ApplicabilityType">
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute type="xs:string" name="matches"/>
        <xs:attribute type="xs:string" name="whenProperty"/>
        <xs:attribute type="xs:string" name="isValue"/>
        <xs:attribute type="xs:string" name="isNotValue"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
  <xs:complexType name="ApplicabilityDefType">
    <xs:sequence>
      <xs:element type="ApplicabilityType" name="Applicability" maxOccurs="unbounded" minOccurs="0" />
      <xs:element type="ApplicabilityDefType" name="ApplicabilityDef" minOccurs="0"/>
    </xs:sequence>
    <xs:attribute type="xs:string" name="mode"/>
    <xs:attribute type="xs:string" name="key"/>
  </xs:complexType>
  <xs:complexType name="ApplicabilityDefsType">
    <xs:sequence>
      <xs:element type="ApplicabilityDefType" name="ApplicabilityDef" maxOccurs="unbounded" minOccurs="0"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="ParamType">
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute type="xs:string" name="value"/>
        <xs:attribute type="xs:string" name="default"/>
        <xs:attribute type="xs:string" name="type"/>
        <xs:attribute type="xs:string" name="name"/>
        <xs:attribute type="xs:string" name="used"/>
        <xs:attribute type="xs:string" name="ref"/>
        <xs:attribute type="xs:string" name="font"/>
        <xs:attribute type="xs:string" name="ioDevice"/>
        <xs:attribute type="xs:string" name="lambda"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
  <xs:complexType name="VariableType" mixed="true">
    <xs:sequence>
      <xs:element type="ParamType" name="Param" minOccurs="0" maxOccurs="unbounded"/>
    </xs:sequence>
    <xs:attribute type="xs:string" name="name"/>
    <xs:attribute type="xs:string" name="type"/>
    <xs:attribute type="xs:string" name="export"/>
    <xs:attribute type="xs:string" name="progmem"/>
    <xs:attribute type="xs:string" name="matches"/>
    <xs:attribute type="xs:string" name="whenProperty"/>
    <xs:attribute type="xs:string" name="isValue"/>
    <xs:attribute type="xs:string" name="isNotValue"/>
    <xs:attribute type="xs:string" name="applicabilityRef"/>
  </xs:complexType>
  <xs:complexType name="GlobalVariablesType">
    <xs:sequence>
      <xs:element type="VariableType" name="Variable" maxOccurs="unbounded" minOccurs="0"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="FunctionType">
    <xs:sequence>
      <xs:element type="ParamType" name="Param" maxOccurs="unbounded" minOccurs="0"/>
    </xs:sequence>
    <xs:attribute type="xs:string" name="name"/>
    <xs:attribute type="xs:string" name="object"/>
    <xs:attribute type="xs:string" name="matches"/>
    <xs:attribute type="xs:string" name="whenProperty"/>
    <xs:attribute type="xs:string" name="isValue"/>
    <xs:attribute type="xs:string" name="isNotValue"/>
    <xs:attribute type="xs:string" name="applicabilityRef"/>
    <xs:attribute type="xs:string" name="pointer"/>
  </xs:complexType>
  <xs:complexType name="LambdaType">
    <xs:sequence>
      <xs:element type="ParamType" name="Param" maxOccurs="unbounded" minOccurs="0"/>
      <xs:element type="FunctionType" name="Function" minOccurs="0" maxOccurs="unbounded"/>
    </xs:sequence>
    <xs:attribute type="xs:string" name="name"/>
    <xs:attribute type="xs:string" name="object"/>
    <xs:attribute type="xs:string" name="matches"/>
    <xs:attribute type="xs:string" name="whenProperty"/>
    <xs:attribute type="xs:string" name="isValue"/>
    <xs:attribute type="xs:string" name="isNotValue"/>
    <xs:attribute type="xs:string" name="applicabilityRef"/>
  </xs:complexType>
  <xs:complexType name="SetupFunctionsType">
    <xs:choice maxOccurs="unbounded" minOccurs="0">
      <xs:element type="FunctionType" name="Function" maxOccurs="unbounded" minOccurs="0"/>
      <xs:element type="LambdaType" name="Lambda"/>
    </xs:choice>
  </xs:complexType>
  <xs:complexType name="TcMenuPluginType">
    <xs:sequence>
      <xs:element type="SupportedPlatformsType" name="SupportedPlatforms"/>
      <xs:element type="xs:string" name="Description"/>
      <xs:element type="DocumentationType" name="Documentation"/>
      <xs:element type="RequiredLibrariesType" name="RequiredLibraries"/>
      <xs:element type="xs:string" name="ImageFile"/>
      <xs:element type="PropertiesType" name="Properties"/>
      <xs:element type="ApplicabilityDefsType" name="ApplicabilityDefs"/>
      <xs:element type="SourceFilesType" name="SourceFiles"/>
      <xs:element type="IncludeFilesType" name="IncludeFiles"/>
      <xs:element type="GlobalVariablesType" name="GlobalVariables"/>
      <xs:element type="SetupFunctionsType" name="SetupFunctions"/>
    </xs:sequence>
    <xs:attribute type="xs:string" name="name"/>
    <xs:attribute type="xs:string" name="id"/>
    <xs:attribute type="xs:string" name="subsystem"/>
    <xs:attribute type="xs:string" name="requiresDesigner"/>
    <xs:attribute type="xs:string" name="needsTheme"/>
  </xs:complexType>
</xs:schema>

=== TcMenu/tcMenu/xmlPlugins/core-display/EmbeddedJFX.xml
<TcMenuPlugin name="Embedded OpenJDK / JavaFX renderer" id="59f05a22-8873-4bfe-86d4-73ef874a0283" subsystem="DISPLAY" needsTheme="false"
              xmlns="https://www.thecoderscorner.com/libraries/tcmenuPluginItem" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
              xsi:schemaLocation="https://www.thecoderscorner.com/libraries/tcmenuPluginItem https://tcmenu.github.io/documentation/arduino-libraries/libraries/tcmenu-plugin-item.xsd">
    <SupportedPlatforms>
        <Platform>RASPBERRY_PIJ</Platform>
    </SupportedPlatforms>
    <Description>JavaFX application and framework that can be used to render the menu onto an embedded Linux device such as a Raspberry PI.</Description>
    <Documentation link="https://tcmenu.github.io/documentation/arduino-libraries/tc-menu/tcmenu-plugins/tcmenu-openjfx-raspberrypi-plugin/"/>
    <RequiredLibraries/>
    <ImageFile>embedded-java.png</ImageFile>

    <Properties>
        <Property id="JDK_INCLUDES_JAVAFX" name="%java.includes.openjfx" initial="false"  type="boolean"
                  desc="%java.includes.openjfx.desc"/>
    </Properties>

    <ApplicabilityDefs/>

    <SourceFiles>
        <Replacement find="PACKAGE_NAME_REPLACEMENT" replace="${NAMESPACE}"/>
        <SourceFile name="emb_jfx/JfxLocalAutoUI.java" />
        <SourceFile name="emb_jfx/LocalTreeComponentManager.java" />
    </SourceFiles>

    <IncludeFiles>
        <!-- dependencies needed for just in time UI -->
        <Header name="${NAMESPACE}.tcmenu.plugins.*" inSource="true"/>
        <Header name="javafx.application.Application" inSource="true"/>
        <Header name="mvn:com.thecoderscorner.tcmenu/embedCONTROLCore@${tcmenu.api.version}" inSource="false"/>
        <Header name="mvn:org.openjfx/javafx-controls@${jfx.version}" inSource="false" whenProperty="JDK_INCLUDES_JAVAFX" isValue="false" />
        <Header name="mvn:org.openjfx/javafx-fxml@${jfx.version}" inSource="false" whenProperty="JDK_INCLUDES_JAVAFX" isValue="false"/>
        <Header name="mod:requires:javafx.graphics" inSource="false"/>
        <Header name="mod:requires:javafx.base" inSource="false"/>
        <Header name="mod:requires:javafx.controls" inSource="false"/>
        <Header name="mod:requires:javafx.fxml" inSource="false"/>
    </IncludeFiles>

    <GlobalVariables>
    </GlobalVariables>

    <SetupFunctions>
        <Function object="JfxLocalAutoUI" name="setAppContext" >
            <Param value="context"/>
        </Function>

        <Function object="Application" name="launch" neverReturns="true">
            <Param value="JfxLocalAutoUI.class"/>
        </Function>
    </SetupFunctions>
</TcMenuPlugin>

=== TcMenu/tcMenu/xmlPlugins/core-themes/NoThemeSelected.xml
<TcMenuPlugin name="%theme.not.required" id="2026a7f2-0d5b-43f5-9f98-4f0eacac4c0e"
              subsystem="THEME" requiresDesigner="2.0"
              xmlns="https://www.thecoderscorner.com/libraries/tcmenuPluginItem" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
              xsi:schemaLocation="https://www.thecoderscorner.com/libraries/tcmenuPluginItem https://tcmenu.github.io/documentation/arduino-libraries/libraries/tcmenu-plugin-item.xsd">
    <SupportedPlatforms>
       <All/>
    </SupportedPlatforms>
    <Description>%theme.not.required.desc</Description>
    <Documentation link="https://tcmenu.github.io/documentation/arduino-libraries/tc-menu/rendering-with-tcmenu-lcd-tft-oled/"/>
    <RequiredLibraries/>
    <ImageFile>no-theme.png</ImageFile>

    <Properties/>

    <ApplicabilityDefs/>

    <SourceFiles/>

    <IncludeFiles/>

    <GlobalVariables/>

    <SetupFunctions/>

</TcMenuPlugin>

=== TcMenu/tcMenu/xmlPlugins/core-display/customDisplay.xml
<TcMenuPlugin name="Completely custom rendering starting from scratch"
              id="8f4821df-c98e-4761-b824-898482df33a5" subsystem="DISPLAY"
              xmlns="https://www.thecoderscorner.com/libraries/tcmenuPluginItem" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
              xsi:schemaLocation="https://www.thecoderscorner.com/libraries/tcmenuPluginItem https://www.thecoderscorner.com/libraries/tcmenu-plugin-item.xsd">
    <SupportedPlatforms>
       <Platform>ARDUINO_UNO</Platform>
       <Platform>ARDUINO_AVR</Platform>
       <Platform>ARDUINO_32</Platform>
       <Platform>ARDUINO_ESP8266</Platform>
       <Platform>ARDUINO_ESP32</Platform>
       <Platform>MBED_RTOS</Platform>
    </SupportedPlatforms>
    <Description>Advanced library usage (prefer customDrawable for most graphical drivers). This allows you to write a custom renderer from scratch, see the documentation link.</Description>
    <Documentation link="https://www.thecoderscorner.com/products/arduino-libraries/tc-menu/customise-menu-input-display-plugin/"/>
    <RequiredLibraries/>
    <ImageFile>custom-display.jpg</ImageFile>

    <Properties>
        <Property id="HEADER_FILE" name="Renderer Header File" initial="" desc="Header file needed for compilation" type="header"/>
        <Property id="CLASS_NAME" name="Renderer Class Type" initial="" desc="The class type for your renderer" type="variable"/>
    </Properties>

    <ApplicabilityDefs/>

    <SourceFiles/>

    <IncludeFiles>
        <Header name="BaseRenderer.h" inSource="false"/>
        <Header name="${HEADER_FILE}.h" inSource="true"/>
    </IncludeFiles>

    <GlobalVariables>
        <Variable name="renderer" type="${CLASS_NAME}" export="only" progmem="false"/>
    </GlobalVariables>

    <SetupFunctions/>
</TcMenuPlugin>

=== TcMenu/tcMenu/xmlPlugins/core-display/oneButtonSwitchesInput.xml
<TcMenuPlugin name="%one.button.name"
              id="4F92CBC0-D13A-4090-9B86-C1952FE42D9B" subsystem="INPUT"
              requiresDesigner="2.2"
              xmlns="https://www.thecoderscorner.com/libraries/tcmenuPluginItem" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
              xsi:schemaLocation="https://www.thecoderscorner.com/libraries/tcmenuPluginItem https://tcmenu.github.io/documentation/arduino-libraries/libraries/tcmenu-plugin-item.xsd">
    <SupportedPlatforms>
        <PlatformGroup>Arduino</PlatformGroup>
        <PlatformGroup>TrueCpp</PlatformGroup>
    </SupportedPlatforms>
    <Description>%one.button.desc</Description>
    <Documentation link="https://tcmenu.github.io/documentation/arduino-libraries/tc-menu/tcmenu-plugins/encoder-switches-input-plugin/"/>
    <RequiredLibraries/>
    <ImageFile>user-button.jpg</ImageFile>

    <Properties>
        <Property id="SW_POLLING_MODE" name="%core.input.polling" initial="SWITCHES_POLL_EVERYTHING" desc="%core.input.polling.desc" type="choice">
            <Choices>
                <Choice desc="%core.input.polling.none">SWITCHES_NO_POLLING</Choice>
                <Choice desc="%core.input.polling.all">SWITCHES_POLL_EVERYTHING</Choice>
                <Choice desc="%core.input.polling.keys">SWITCHES_POLL_KEYS_ONLY</Choice>
            </Choices>
        </Property>
        <Property id="SWITCH_IODEVICE" name="%core.switch.io.device" initial="devicePins" desc="%core.switch.io.device.desc" type="io-device"/>
        <Property id="BUTTON_PIN" name="%one.button.pin" initial="2" desc="%one.button.pin" type="pin"/>
        <Property id="PULLUP_LOGIC" name="%core.pullup.logic" initial="true" desc="%core.pullup.logic.desc" type="boolean"/>
        <Property id="DOUBLE_CLICK_THRESHOLD" name="%double.click.threshold" initial="true" desc="%double.click.threshold" type="int" min="100" max="1000"/>
    </Properties>

    <ApplicabilityDefs/>

    <SourceFiles/>

    <IncludeFiles>
        <Header name="extras/TcOneButtonHandler.h" inSource="false" />
    </IncludeFiles>

    <GlobalVariables>
        <Variable name="oneButtonHandler" export="true" type="TcOneButtonHandler">
            <Param value="${BUTTON_PIN}"/>
            <Param value="${DOUBLE_CLICK_THRESHOLD}"/>
        </Variable>
    </GlobalVariables>

    <SetupFunctions>
        <Function name="init" object="switches">
            <Param ioDevice="${SWITCH_IODEVICE}" />
            <Param value="${SW_POLLING_MODE}" />
            <Param value="${PULLUP_LOGIC}"/>
        </Function>

        <Function name="initWithoutInput" object="menuMgr" >
            <Param ref="renderer"/>
            <Param ref="${ROOT}"/>
        </Function>

        <Function name="start" object="oneButtonHandler"/>
    </SetupFunctions>
</TcMenuPlugin>

=== TcMenu/tcMenu/xmlPlugins/core-themes/ManualTheme.xml
<TcMenuPlugin name="%theme.manual" id="b186c809-d9ef-4ca8-9d4b-e4780a041ccc"
              subsystem="THEME" requiresDesigner="2.0"
              xmlns="https://www.thecoderscorner.com/libraries/tcmenuPluginItem" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
              xsi:schemaLocation="https://www.thecoderscorner.com/libraries/tcmenuPluginItem https://tcmenu.github.io/documentation/arduino-libraries/libraries/tcmenu-plugin-item.xsd">
    <SupportedPlatforms>
       <All/>
    </SupportedPlatforms>
    <Description>%theme.manual.desc</Description>
    <Documentation link="https://tcmenu.github.io/documentation/arduino-libraries/tc-menu/rendering-with-tcmenu-lcd-tft-oled/"/>
    <RequiredLibraries/>
    <ImageFile>no-theme.png</ImageFile>

    <Properties/>

    <ApplicabilityDefs/>

    <SourceFiles/>

    <IncludeFiles/>

    <GlobalVariables/>

    <SetupFunctions/>

</TcMenuPlugin>

=== TcMenu/tcMenu/xmlPlugins/core-themes/CoolBlueModern.xml
<TcMenuPlugin name="%theme.cool.blue.modern.name" id="850dc0a3-f534-47c2-94d8-1e64ff368a54"
              subsystem="THEME" requiresDesigner="2.0"
              xmlns="https://www.thecoderscorner.com/libraries/tcmenuPluginItem" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
              xsi:schemaLocation="https://www.thecoderscorner.com/libraries/tcmenuPluginItem https://www.thecoderscorner.com/products/arduino-libraries/libraries/tcmenu-plugin-item.xsd">
    <SupportedPlatforms>
       <All/>
    </SupportedPlatforms>
    <Description>%theme.cool.blue.modern.desc</Description>
    <Documentation link="https://www.thecoderscorner.com/products/arduino-libraries/tc-menu/themes/color-themes-for-all-display-sizes/"/>
    <RequiredLibraries/>
    <ImageFile>theme-cool-blue-modern.jpg</ImageFile>

    <Properties>
        <Property id="ITEM_FONT" name="%theme.item.font" initial="def:,1" desc="%theme.item.font.desc" type="font"/>
        <Property id="TITLE_FONT" name="%theme.title.font" initial="def:,1" desc="%theme.title.font.desc" type="font"/>
        <Property id="BORDER_FOR_ACTIONS" name="%theme.border.for.action" initial="0" desc="%theme.border.for.action.desc" type="int" min="0" max="3"/>
        <Property id="TITLE_SHOW_MODE" name="%theme.title.show.mode" initial="TITLE_FIRST_ROW" desc="%theme.title.show.mode.desc" type="choice">
            <Choices>
                <Choice desc="%theme.title.none">NO_TITLE</Choice>
                <Choice desc="%theme.title.first.row">TITLE_FIRST_ROW</Choice>
                <Choice desc="%theme.title.always">TITLE_ALWAYS</Choice>
            </Choices>
        </Property>
        <Property id="USE_TC_UNICODE" name="%theme.use.tcunicode" initial="false" type="boolean" desc="%theme.use.tcunicode.desc"/>
        <Property id="USE_SLIDER_ANALOG" name="%theme.use.sliders" initial="true" desc="%theme.use.sliders.desc" type="boolean"/>
        <Property id="NEED_EDITING_ICONS" name="%theme.need.edit.icons" initial="false" desc="theme.need.edit.icons.desc" type="boolean"/>
    </Properties>

    <ApplicabilityDefs/>

    <SourceFiles>
        <Replacement find="ACTION_BORDER_WIDTH 0" replace="ACTION_BORDER_WIDTH ${BORDER_FOR_ACTIONS}"/>
        <SourceFile name="coolBlue/ThemeCoolBlueModern.h" overwrite="false"/>
    </SourceFiles>

    <IncludeFiles>
        <Header name="${SRC_DIR_OFFSET}ThemeCoolBlueModern.h" inSource="cppSrc"/>
        <Header name="tcUnicodeHelper.h" inSource="false" priority="high" whenProperty="USE_TC_UNICODE" isValue="true" />
        <Header name="${ITEM_FONT}" inSource="font"/>
        <Header name="${TITLE_FONT}" inSource="font"/>
    </IncludeFiles>

    <GlobalVariables>
        <Variable name="${ITEM_FONT}" export="font" whenProperty="ITEM_FONT" matches="ad[al]:.*" />
        <Variable name="${TITLE_FONT}" export="font" whenProperty="ITEM_FONT" matches="ad[al]:.*" />
    </GlobalVariables>

    <SetupFunctions>
        <Function name="setTitleMode" object="renderer">
            <Param name="BaseGraphicalRenderer::${TITLE_SHOW_MODE}"/>
        </Function>

        <Function name="setUseSliderForAnalog" object="renderer">
            <Param name="${USE_SLIDER_ANALOG}"/>
        </Function>

        <Function name="enableTcUnicode" object="renderer" whenProperty="USE_TC_UNICODE" isValue="true"/>

        <Function name="installCoolBlueModernTheme">
            <Param value="renderer"/>
            <Param font="${ITEM_FONT}"/>
            <Param font="${TITLE_FONT}"/>
            <Param value="${NEED_EDITING_ICONS}"/>
        </Function>

    </SetupFunctions>
</TcMenuPlugin>

=== TcMenu/tcMenu/xmlPlugins/core-remote/JavaWebServerRemote.xml
<TcMenuPlugin name="Serve up embedCONTROL JS from webserver" id="36f98a10-7ffc-468c-8b6b-3961b5c87cbe" subsystem="REMOTE"
              xmlns="https://www.thecoderscorner.com/libraries/tcmenuPluginItem" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
              xsi:schemaLocation="https://www.thecoderscorner.com/libraries/tcmenuPluginItem https://www.thecoderscorner.com/libraries/tcmenu-plugin-item.xsd">
    <SupportedPlatforms>
        <Platform>RASPBERRY_PIJ</Platform>
    </SupportedPlatforms>
    <Description>Control your embedded device remotely using embedCONTROL JS served up using a Jetty webserver. A lightweight React.JS app is served that needs no installation.</Description>
    <Documentation link="https://www.thecoderscorner.com/products/arduino-libraries/tc-menu/tcmenu-iot/embedcontroljs-webserver-plugin/"/>
    <RequiredLibraries/>
    <ImageFile>embedCONTROLJS.png</ImageFile>

    <Properties>
        <Property id="EJ_WWW_STATIC_DIR" name="Webserver static files directory" initial="./data/www" type="text"
                  desc="The filesystem location of the static files, usually relative to the app start directory"/>
        <Property id="EJ_WEB_SERVER_PORT" name="HTTP port to listen on" initial="8080" type="int"
                  desc="Port on which to listen for HTTP requests, to listen on port 80 we recommend a proxy"/>
        <Property id="EJ_DIRECTORY_LISTING" name="List directories in webserver" initial="false" type="boolean"
                  desc="Turn on or off directory listing when no index file exists"/>
    </Properties>

    <ApplicabilityDefs/>

    <SourceFiles>
        <ZipDataFile name="embedCONTROL.zip" dest="${EJ_WWW_STATIC_DIR}"/>
    </SourceFiles>

    <IncludeFiles>
        <Header name="mvn:org.eclipse.jetty/jetty-server@10.0.9" inSource="false"/>
        <Header name="mvn:org.eclipse.jetty.websocket/websocket-javax-server@10.0.9" inSource="false"/>
        <Header name="mvn:org.slf4j/slf4j-jdk14@1.7.36" inSource="false"/>

        <Header name="mod:requires:org.eclipse.jetty.server" inSource="false"/>
        <Header name="mod:requires:org.eclipse.jetty.servlet" inSource="false"/>
        <Header name="mod:requires:jetty.websocket.api" inSource="false"/>
        <Header name="mod:requires:org.eclipse.jetty.websocket.javax.server" inSource="false"/>
    </IncludeFiles>

    <GlobalVariables>
        <Variable name="tagVal" type="ConfigurableProtocolConverter" inContext="true" export="false"/>

        <Variable name="webServer" type="TcJettyWebServer" export="true" inContext="true" >
            <Param ref="ConfigurableProtocolConverter.class" name="protocol" type="ConfigurableProtocolConverter"/>
            <Param ref="Clock.class" name="clock" type="Clock"/>
            <Param value="${EJ_WWW_STATIC_DIRECTORY}" name="dataDir"/>
            <Param value="${EJ_WEB_SOCKET_PORT}" name="wsPort"/>
        </Variable>
    </GlobalVariables>

    <SetupFunctions>
        <Function name="addConnectionManager" object="manager">
            <Param value="webServer"/>
        </Function>
    </SetupFunctions>
</TcMenuPlugin>

=== TcMenu/tcMenu/xmlPlugins/core-display/ssd1306asciiDisplay.xml
<!--
  ~ Copyright (c)  2016-2020 https://www.thecoderscorner.com (Dave Cherry).
  ~ This product is licensed under an Apache license, see the LICENSE file in the top-level directory.
  ~
  -->

<TcMenuPlugin name="%ssd1306ascii.name" id="1ec1b247-cc51-49d7-aa5c-dd0d4530751d" subsystem="DISPLAY"
              xmlns="https://www.thecoderscorner.com/libraries/tcmenuPluginItem" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
              xsi:schemaLocation="https://www.thecoderscorner.com/libraries/tcmenuPluginItem https://tcmenu.github.io/documentation/arduino-libraries/libraries/tcmenu-plugin-item.xsd">
    <SupportedPlatforms>
        <Platform>ARDUINO_UNO</Platform>
        <Platform>ARDUINO_AVR</Platform>
    </SupportedPlatforms>
    <Description>%ssd1306ascii.desc</Description>
    <Documentation link="https://tcmenu.github.io/documentation/arduino-libraries/tc-menu/tcmenu-plugins/ssd1306ascii-display-plugin/"/>
    <RequiredLibraries/>
    <ImageFile>ssd1306ascii.jpg</ImageFile>

    <Properties>
        <Property id="DISPLAY_VARIABLE" name="%core.display.variable" initial="gfx" desc="%core.display.variable.desc" type="variable" />
        <Property id="DISPLAY_TYPE" name="%core.display.variable.type" initial="" desc="%core.display.variable.type.desc" type="variable" />
        <Property id="CHAR_WIDTH" name="%ssd1306ascii.char.width" initial="20" desc="%ssd1306ascii.char.width.desc" type="int" min="2" max="99"/>
        <Property id="TITLE_FONT" name="%ssd1306ascii.title.font" initial="Arial14" desc="%ssd1306ascii.title.font.desc" type="variable" />
        <Property id="ITEM_FONT" name="%ssd1306ascii.item.font" initial="System5x7" desc="%ssd1306ascii.item.font.desc" type="variable" />
    </Properties>
    <ApplicabilityDefs/>

    <SourceFiles>
        <SourceFile name="ssd1306AsciiSupport/ssd1306asciiRenderer.cpp" />
        <SourceFile name="ssd1306AsciiSupport/ssd1306asciiRenderer.h" />
    </SourceFiles>

    <IncludeFiles>
        <Header name="SSD1306Ascii.h" inSource="false" priority="high"/>
        <Header name="${DISPLAY_TYPE}.h" inSource="false"/>
        <Header name="ssd1306asciiRenderer.h" inSource="true"/>
    </IncludeFiles>

    <GlobalVariables>
        <Variable name="${DISPLAY_VARIABLE}" type="${DISPLAY_TYPE}" export="only" />
        <Variable name="renderer" type="SSD1306AsciiRenderer" export="true" progmem="false">
            <Param value="${CHAR_WIDTH}"/>
            <Param value="${TITLE_FONT}"/>
            <Param value="${ITEM_FONT}"/>
        </Variable>
    </GlobalVariables>

    <SetupFunctions>
        <Function name="setGraphicsDevice" object="renderer" whenProperty="DISPLAY_CONFIG" isValue="">
            <Param ref="${DISPLAY_VARIABLE}"/>
        </Function>
    </SetupFunctions>
</TcMenuPlugin>
