=== TcMenu/tcMenu/xmlPlugins/tcmenu-plugin-item.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema"
           targetNamespace="https://www.thecoderscorner.com/libraries/tcmenuPluginItem"
           xmlns="https://www.thecoderscorner.com/libraries/tcmenuPluginItem">
  <xs:element name="TcMenuPlugin" type="TcMenuPluginType"/>
  <xs:complexType name="SupportedPlatformsType">
    <xs:sequence>
      <xs:element name="Platform" maxOccurs="unbounded" minOccurs="0">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:enumeration value="ARDUINO_UNO"/>
            <xs:enumeration value="ARDUINO_AVR"/>
            <xs:enumeration value="ARDUINO_32"/>
            <xs:enumeration value="ARDUINO_ESP8266"/>
            <xs:enumeration value="ARDUINO_ESP32"/>
            <xs:enumeration value="STM32DUINO"/>
            <xs:enumeration value="RASPBERRY_PIJ"/>
            <xs:enumeration value="MBED_RTOS"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="DocumentationType">
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute type="xs:string" name="link"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
  <xs:complexType name="RequiredLibrariesType">
    <xs:sequence>
      <xs:element name="Library" type="xs:string" maxOccurs="unbounded" minOccurs="0">
      </xs:element>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="PropertyType" mixed="true">
    <xs:sequence>
      <xs:element type="ChoicesType" name="Choices" minOccurs="0"/>
    </xs:sequence>
    <xs:attribute type="xs:string" name="id" use="required"/>
    <xs:attribute type="xs:string" name="name" use="required"/>
    <xs:attribute type="xs:string" name="initial" use="required"/>
    <xs:attribute type="xs:string" name="desc" use="required"/>
    <xs:attribute type="xs:string" name="type" use="required"/>
    <xs:attribute type="xs:string" name="min"/>
    <xs:attribute type="xs:string" name="max"/>
    <xs:attribute type="xs:string" name="matches"/>
    <xs:attribute type="xs:string" name="whenProperty"/>
    <xs:attribute type="xs:string" name="isValue"/>
    <xs:attribute type="xs:string" name="isNotValue"/>
  </xs:complexType>
  <xs:complexType name="ChoiceType">
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute name="desc" type="xs:string"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
  <xs:complexType name="ChoicesType">
    <xs:sequence>
      <xs:element name="Choice" type="ChoiceType" maxOccurs="unbounded" minOccurs="0"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="PropertiesType">
    <xs:sequence>
      <xs:element type="PropertyType" name="Property" maxOccurs="unbounded" minOccurs="0"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="ReplacementType">
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute type="xs:string" name="find" use="required"/>
        <xs:attribute type="xs:string" name="replace" use="required"/>
        <xs:attribute type="xs:string" name="whenProperty"/>
        <xs:attribute type="xs:string" name="matches"/>
        <xs:attribute type="xs:string" name="isValue"/>
        <xs:attribute type="xs:string" name="isNotValue"/>
        <xs:attribute type="xs:string" name="applicabilityRef"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
  <xs:complexType name="SourceFileType" mixed="true">
    <xs:attribute type="xs:string" name="name" use="required"/>
    <xs:attribute type="xs:string" name="matches"/>
    <xs:attribute type="xs:string" name="whenProperty"/>
    <xs:attribute type="xs:string" name="isValue"/>
    <xs:attribute type="xs:string" name="isNotValue"/>
    <xs:attribute type="xs:string" name="applicabilityRef"/>
    <xs:attribute type="xs:string" name="overwrite"/>
  </xs:complexType>
  <xs:complexType name="SourceFilesType">
    <xs:sequence>
      <xs:element type="ReplacementType" name="Replacement" maxOccurs="unbounded" minOccurs="0"/>
      <xs:element type="SourceFileType" name="SourceFile" maxOccurs="unbounded" minOccurs="0"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="HeaderType">
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute type="xs:string" name="name" use="required"/>
        <xs:attribute type="xs:string" name="inSource" use="required"/>
        <xs:attribute type="xs:string" name="priority"/>
        <xs:attribute type="xs:string" name="matches"/>
        <xs:attribute type="xs:string" name="whenProperty"/>
        <xs:attribute type="xs:string" name="isValue"/>
        <xs:attribute type="xs:string" name="isNotValue"/>
        <xs:attribute type="xs:string" name="applicabilityRef"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
  <xs:complexType name="IncludeFilesType">
    <xs:sequence>
      <xs:element type="HeaderType" name="Header" maxOccurs="unbounded" minOccurs="0" />
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="ApplicabilityType">
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute type="xs:string" name="matches"/>
        <xs:attribute type="xs:string" name="whenProperty"/>
        <xs:attribute type="xs:string" name="isValue"/>
        <xs:attribute type="xs:string" name="isNotValue"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
  <xs:complexType name="ApplicabilityDefType">
    <xs:sequence>
      <xs:element type="ApplicabilityType" name="Applicability" maxOccurs="unbounded" minOccurs="0" />
      <xs:element type="ApplicabilityDefType" name="ApplicabilityDef" minOccurs="0"/>
    </xs:sequence>
    <xs:attribute type="xs:string" name="mode"/>
    <xs:attribute type="xs:string" name="key"/>
  </xs:complexType>
  <xs:complexType name="ApplicabilityDefsType">
    <xs:sequence>
      <xs:element type="ApplicabilityDefType" name="ApplicabilityDef" maxOccurs="unbounded" minOccurs="0"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="ParamType">
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute type="xs:string" name="value"/>
        <xs:attribute type="xs:string" name="default"/>
        <xs:attribute type="xs:string" name="type"/>
        <xs:attribute type="xs:string" name="name"/>
        <xs:attribute type="xs:string" name="used"/>
        <xs:attribute type="xs:string" name="ref"/>
        <xs:attribute type="xs:string" name="font"/>
        <xs:attribute type="xs:string" name="ioDevice"/>
        <xs:attribute type="xs:string" name="lambda"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
  <xs:complexType name="VariableType" mixed="true">
    <xs:sequence>
      <xs:element type="ParamType" name="Param" minOccurs="0" maxOccurs="unbounded"/>
    </xs:sequence>
    <xs:attribute type="xs:string" name="name"/>
    <xs:attribute type="xs:string" name="type"/>
    <xs:attribute type="xs:string" name="export"/>
    <xs:attribute type="xs:string" name="progmem"/>
    <xs:attribute type="xs:string" name="matches"/>
    <xs:attribute type="xs:string" name="whenProperty"/>
    <xs:attribute type="xs:string" name="isValue"/>
    <xs:attribute type="xs:string" name="isNotValue"/>
    <xs:attribute type="xs:string" name="applicabilityRef"/>
  </xs:complexType>
  <xs:complexType name="GlobalVariablesType">
    <xs:sequence>
      <xs:element type="VariableType" name="Variable" maxOccurs="unbounded" minOccurs="0"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="FunctionType">
    <xs:sequence>
      <xs:element type="ParamType" name="Param" maxOccurs="unbounded" minOccurs="0"/>
    </xs:sequence>
    <xs:attribute type="xs:string" name="name"/>
    <xs:attribute type="xs:string" name="object"/>
    <xs:attribute type="xs:string" name="matches"/>
    <xs:attribute type="xs:string" name="whenProperty"/>
    <xs:attribute type="xs:string" name="isValue"/>
    <xs:attribute type="xs:string" name="isNotValue"/>
    <xs:attribute type="xs:string" name="applicabilityRef"/>
    <xs:attribute type="xs:string" name="pointer"/>
  </xs:complexType>
  <xs:complexType name="LambdaType">
    <xs:sequence>
      <xs:element type="ParamType" name="Param" maxOccurs="unbounded" minOccurs="0"/>
      <xs:element type="FunctionType" name="Function" minOccurs="0" maxOccurs="unbounded"/>
    </xs:sequence>
    <xs:attribute type="xs:string" name="name"/>
    <xs:attribute type="xs:string" name="object"/>
    <xs:attribute type="xs:string" name="matches"/>
    <xs:attribute type="xs:string" name="whenProperty"/>
    <xs:attribute type="xs:string" name="isValue"/>
    <xs:attribute type="xs:string" name="isNotValue"/>
    <xs:attribute type="xs:string" name="applicabilityRef"/>
  </xs:complexType>
  <xs:complexType name="SetupFunctionsType">
    <xs:choice maxOccurs="unbounded" minOccurs="0">
      <xs:element type="FunctionType" name="Function" maxOccurs="unbounded" minOccurs="0"/>
      <xs:element type="LambdaType" name="Lambda"/>
    </xs:choice>
  </xs:complexType>
  <xs:complexType name="TcMenuPluginType">
    <xs:sequence>
      <xs:element type="SupportedPlatformsType" name="SupportedPlatforms"/>
      <xs:element type="xs:string" name="Description"/>
      <xs:element type="DocumentationType" name="Documentation"/>
      <xs:element type="RequiredLibrariesType" name="RequiredLibraries"/>
      <xs:element type="xs:string" name="ImageFile"/>
      <xs:element type="PropertiesType" name="Properties"/>
      <xs:element type="ApplicabilityDefsType" name="ApplicabilityDefs"/>
      <xs:element type="SourceFilesType" name="SourceFiles"/>
      <xs:element type="IncludeFilesType" name="IncludeFiles"/>
      <xs:element type="GlobalVariablesType" name="GlobalVariables"/>
      <xs:element type="SetupFunctionsType" name="SetupFunctions"/>
    </xs:sequence>
    <xs:attribute type="xs:string" name="name"/>
    <xs:attribute type="xs:string" name="id"/>
    <xs:attribute type="xs:string" name="subsystem"/>
    <xs:attribute type="xs:string" name="requiresDesigner"/>
    <xs:attribute type="xs:string" name="needsTheme"/>
  </xs:complexType>
</xs:schema>

=== TcMenu/tcMenu/xmlPlugins/core-remote/remoteMbedEthernet.xml
<!--
  ~ Copyright (c)  2016-2020 https://www.thecoderscorner.com (Nutricherry LTD).
  ~ This product is licensed under an Apache license, see the LICENSE file in the top-level directory.
  ~
  -->

<TcMenuPlugin name="Ethernet control of your menu using mbed libraries" id="27e7a502-330e-4570-9f8e-bd26ac88051f" subsystem="REMOTE"
              xmlns="https://www.thecoderscorner.com/libraries/tcmenuPluginItem" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
              xsi:schemaLocation="https://www.thecoderscorner.com/libraries/tcmenuPluginItem https://www.thecoderscorner.com/libraries/tcmenu-plugin-item.xsd">
    <SupportedPlatforms>
        <Platform>MBED_RTOS</Platform>
    </SupportedPlatforms>
    <Description>Use this option to be able to control the menu using the mbed ethernet libraries.</Description>
    <Documentation link="https://www.thecoderscorner.com/products/arduino-libraries/tc-menu/tcmenu-plugins/ethernet-remote-plugin/"/>
    <RequiredLibraries/>
    <ImageFile>mbed-ethernet.jpg</ImageFile>

    <Properties>
        <Property id="NUM_CONCURRENT_ETH" name="Number of concurrent connections" desc="The number of concurrent connects to allow, each uses memory" initial="1" type="choice">
            <Choices>
                <Choice desc="One concurrent remote">1</Choice>
                <Choice desc="Two concurrent remotes">2</Choice>
                <Choice desc="Three concurrent remotes">3</Choice>
            </Choices>
        </Property>
        <Property id="LISTEN_PORT" name="Port on which to listen" initial="3333" desc="The port on which to listen" type="int" min="0" max="65535"/>
    </Properties>

    <ApplicabilityDefs/>

    <SourceFiles>
        <SourceFile name="mbedEthernet/MBedEthernetTransport.cpp"/>
        <SourceFile name="mbedEthernet/MBedEthernetTransport.h"/>
    </SourceFiles>

    <IncludeFiles>
        <Header name="MBedEthernetTransport.h" inSource="true"/>
        <Header name="RemoteConnector.h" inSource="false"/>
    </IncludeFiles>

    <GlobalVariables>
        <Variable name="mbedEthInitialisation" type="MbedEthernetInitialisation" export="true">
            <Param value="${LISTEN_PORT}"/>
            <Param value="applicationInfo"/>
        </Variable>

        <Variable name="ethernetTransport" type="EthernetTagValTransport" export="false"/>
        <Variable name="ethernetConnection" type="RemoteServerConnection" export="false">
            <Param value="ethernetTransport"/>
            <Param value="mbedEthInitialisation"/>
        </Variable>

        <Variable name="ethernetTransport2" type="EthernetTagValTransport" export="false" whenProperty="NUM_CONCURRENT_ETH" matches="[23]"/>
        <Variable name="ethernetConnection2" type="RemoteServerConnection" export="false" whenProperty="NUM_CONCURRENT_ETH" matches="[23]">
            <Param value="ethernetTransport2"/>
            <Param value="mbedEthInitialisation"/>
        </Variable>

        <Variable name="ethernetTransport3" type="EthernetTagValTransport" export="false" whenProperty="NUM_CONCURRENT_ETH" isValue="3"/>
        <Variable name="ethernetConnection3" type="RemoteServerConnection" export="false" whenProperty="NUM_CONCURRENT_ETH" isValue="3">
            <Param value="ethernetTransport3"/>
            <Param value="mbedEthInitialisation"/>
        </Variable>

    </GlobalVariables>

    <SetupFunctions>

    </SetupFunctions>
</TcMenuPlugin>

=== TcMenu/tcMenu/xmlPlugins/core-display/customDrawable.xml
<TcMenuPlugin name="%custom.drawable.name"
              id="2202fd9e-3a92-48eb-a70a-8d331793e0b4"
              subsystem="DISPLAY" needsTheme="true"
              xmlns="https://www.thecoderscorner.com/libraries/tcmenuPluginItem" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
              xsi:schemaLocation="https://www.thecoderscorner.com/libraries/tcmenuPluginItem https://www.thecoderscorner.com/products/arduino-libraries/libraries/tcmenu-plugin-item.xsd">
    <SupportedPlatforms>
        <PlatformGroup>Arduino</PlatformGroup>
        <PlatformGroup>TrueCpp</PlatformGroup>
    </SupportedPlatforms>
    <Description>%custom.drawable.desc</Description>
    <Documentation link="https://www.thecoderscorner.com/products/arduino-libraries/tc-menu/customise-menu-input-display-plugin/"/>
    <RequiredLibraries/>
    <ImageFile>custom-display.jpg</ImageFile>

    <Properties>
        <Property id="UPDATES_PER_SEC" name="%core.screen.updates.sec" initial="5" desc="%core.screen.updates.sec.desc" type="int" min="1" max="30"/>
        <Property id="CLASS_NAME" name="%complete.custom.class.name" initial="MyCustomDrawing" desc="%complete.custom.class.name.desc" type="variable"/>
    </Properties>

    <ApplicabilityDefs/>

    <SourceFiles>
        <Replacement find="CustomScreenDrawable" replace="${CLASS_NAME}Drawable" />
        <SourceFile name="emptyDrawable/CustomDisplayDrawable.h" overwrite="false" />
    </SourceFiles>

    <IncludeFiles>
        <Header name="graphics/GraphicsDeviceRenderer.h" inSource="false"/>
        <Header name="${SRC_DIR_OFFSET}CustomDisplayDrawable.h" inSource="cppSrc"/>
    </IncludeFiles>

    <GlobalVariables>
        <Variable name="renderer" type="GraphicsDeviceRenderer" export="true">
            <Param value="30"/>
            <Param value="applicationInfo.name"/>
            <Param value="new ${CLASS_NAME}Drawable()"/>
        </Variable>
    </GlobalVariables>

    <SetupFunctions>
        <Function object="renderer" name="setUpdatesPerSecond">
            <Param value="${UPDATES_PER_SEC}"/>
        </Function>
    </SetupFunctions>
</TcMenuPlugin>

=== TcMenu/tcMenu/xmlPlugins/core-themes/CoolBlueTraditional.xml
<TcMenuPlugin name="DEPRECATED cool blue traditional" id="03c6b25f-db63-402a-8447-a5ce1484c14d"
              subsystem="THEME" requiresDesigner="2.0"
              xmlns="https://www.thecoderscorner.com/libraries/tcmenuPluginItem" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
              xsi:schemaLocation="https://www.thecoderscorner.com/libraries/tcmenuPluginItem https://tcmenu.github.io/documentation/arduino-libraries/libraries/tcmenu-plugin-item.xsd">
    <SupportedPlatforms>
       <All/>
    </SupportedPlatforms>
    <Description>THIS THEME IS DEPRECATED (kept for existing users), cool blue traditional theme</Description>
    <Documentation link="https://tcmenu.github.io/documentation/arduino-libraries/tc-menu/themes/color-themes-for-all-display-sizes/"/>
    <RequiredLibraries/>
    <ImageFile>theme-cool-blue-traditional.jpg</ImageFile>

    <Properties>
        <Property id="ITEM_FONT" name="%theme.item.font" initial="def:,1" desc="%theme.item.font.desc" type="font"/>
        <Property id="TITLE_FONT" name="%theme.title.font" initial="def:,1" desc="%theme.title.font.desc" type="font"/>
        <Property id="BORDER_FOR_ACTIONS" name="%theme.border.for.action" initial="0" desc="%theme.border.for.action.desc" type="int" min="0" max="3"/>
        <Property id="TITLE_SHOW_MODE" name="%theme.title.show.mode" initial="TITLE_FIRST_ROW" desc="%theme.title.show.mode.desc" type="choice">
            <Choices>
                <Choice desc="%theme.title.none">NO_TITLE</Choice>
                <Choice desc="%theme.title.first.row">TITLE_FIRST_ROW</Choice>
                <Choice desc="%theme.title.always">TITLE_ALWAYS</Choice>
            </Choices>
        </Property>
        <Property id="USE_TC_UNICODE" name="%theme.use.tcunicode" initial="false" type="boolean" desc="%theme.use.tcunicode.desc"/>
        <Property id="USE_SLIDER_ANALOG" name="%theme.use.sliders" initial="true" desc="%theme.use.sliders.desc" type="boolean"/>
        <Property id="NEED_EDITING_ICONS" name="%theme.need.edit.icons" initial="true" desc="theme.need.edit.icons.desc" type="boolean"/>
    </Properties>

    <ApplicabilityDefs/>

    <SourceFiles>
        <SourceFile name="coolBlue/ThemeCoolBlueTraditional.h" overwrite="false"/>
    </SourceFiles>

    <IncludeFiles>
        <Header name="${SRC_DIR_OFFSET}ThemeCoolBlueTraditional.h" inSource="cppSrc"/>
        <Header name="tcUnicodeHelper.h" inSource="false" priority="high" whenProperty="USE_TC_UNICODE" isValue="true" />
        <Header name="${ITEM_FONT}" inSource="font"/>
        <Header name="${TITLE_FONT}" inSource="font"/>
    </IncludeFiles>

    <GlobalVariables>
        <Variable name="${ITEM_FONT}" export="font" whenProperty="ITEM_FONT" matches="ad[al]:.*" />
        <Variable name="${TITLE_FONT}" export="font" whenProperty="ITEM_FONT" matches="ad[al]:.*" />
    </GlobalVariables>

    <SetupFunctions>
        <Function name="setTitleMode" object="renderer">
            <Param name="BaseGraphicalRenderer::${TITLE_SHOW_MODE}"/>
        </Function>

        <Function name="setUseSliderForAnalog" object="renderer">
            <Param name="${USE_SLIDER_ANALOG}"/>
        </Function>

        <Function name="enableTcUnicode" object="renderer" whenProperty="USE_TC_UNICODE" isValue="true"/>

        <Function name="installCoolBlueTraditionalTheme">
            <Param value="renderer"/>
            <Param font="${ITEM_FONT}"/>
            <Param font="${TITLE_FONT}"/>
            <Param value="${NEED_EDITING_ICONS}"/>
        </Function>
    </SetupFunctions>
</TcMenuPlugin>

=== TcMenu/tcMenu/xmlPlugins/core-display/noDisplay.xml
<TcMenuPlugin name="%core.no.display" id="cdd0be35-f6ff-40ae-86fc-f9d04a6e8679" subsystem="DISPLAY"
              xmlns="https://www.thecoderscorner.com/libraries/tcmenuPluginItem" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
              xsi:schemaLocation="https://www.thecoderscorner.com/libraries/tcmenuPluginItem https://tcmenu.github.io/documentation/arduino-libraries/libraries/tcmenu-plugin-item.xsd">
    <SupportedPlatforms>
       <All/>
    </SupportedPlatforms>
    <Description>%core.no.display.desc</Description>
    <Documentation link="https://tcmenu.github.io/documentation/arduino-libraries/tc-menu/tcmenu-plugins/customise-menu-input-display-plugin/"/>
    <RequiredLibraries/>
    <ImageFile>no-display.png</ImageFile>

    <Properties/>

    <ApplicabilityDefs/>

    <SourceFiles/>

    <IncludeFiles>
        <Header name="BaseRenderers.h" inSource="false" whenProperty="TARGET" isNotValue="RASPBERRY_PIJ"/>
    </IncludeFiles>

    <GlobalVariables>

        <Variable name="renderer" type="NoRenderer" export="true" progmem="false" whenProperty="TARGET" isNotValue="RASPBERRY_PIJ"/>
    </GlobalVariables>

    <SetupFunctions>
        <!-- For Embedded Java normally the display starts the menu, to keep the ordering intact, for no-display we must do it -->
        <Function object="MenuManager.class" name="start" whenProperty="TARGET" isValue="RASPBERRY_PIJ"/>
    </SetupFunctions>
</TcMenuPlugin>

=== TcMenu/tcMenu/xmlPlugins/core-remote/remoteSerialESP.xml
<TcMenuPlugin name="ESP Serial remote control (Rs232 / USB / Bluetooth)" id="ba23b2a7-040e-40e2-8fae-d45c82cf450b" subsystem="REMOTE"
              xmlns="https://www.thecoderscorner.com/libraries/tcmenuPluginItem" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
              xsi:schemaLocation="https://www.thecoderscorner.com/libraries/tcmenuPluginItem https://tcmenu.github.io/documentation/arduino-libraries/libraries/tcmenu-plugin-item.xsd">
    <SupportedPlatforms>
        <Platform>ARDUINO_ESP8266</Platform>
        <Platform>ARDUINO_ESP32</Platform>
    </SupportedPlatforms>
    <Description>Use this option to be able to control the menu over many kinds of serial link from ESP boards, for example RS232, USBSerial, Bluetooth. The full menu structure will be available to the remote using either the protocol or the API..</Description>
    <Documentation link="https://tcmenu.github.io/documentation/arduino-libraries/tc-menu/tcmenu-iot/serial-remote-plugin/"/>
    <RequiredLibraries/>
    <ImageFile>serial-connection.jpg</ImageFile>

    <Properties>
        <Property id="SERIAL_PORT" name="Serial port" desc="Enter the variable name of the serial port. E.G: Serial" initial="Serial" type="variable"/>
        <Property id="HARDWARE_PORT" name="Is Hardware Port" desc="The port is a hardware serial port (see HardwareSerial)" initial="true" type="boolean"/>
    </Properties>

    <ApplicabilityDefs/>

    <SourceFiles>
        <Replacement find="Stream&#92;*" replace="HardwareSerial*" whenProperty="HARDWARE_PORT" isValue="true"/>
        <Replacement find="serialPort->availableForWrite() != 0" replace="true" whenProperty="HARDWARE_PORT" isValue="false"/>
        <SourceFile name="serialSrc/SerialTransport.cpp"/>
        <SourceFile name="serialSrc/SerialTransport.h"/>
    </SourceFiles>

    <IncludeFiles>
        <Header name="RemoteConnector.h" inSource="false"/>
        <Header name="SerialTransport.h" inSource="true"/>
    </IncludeFiles>

    <GlobalVariables>
        <Variable name="serialInitializer" type="NoInitialisationNeeded"/>

        <Variable name="serialTransport" type="SerialTagValueTransport">
            <Param ref="${SERIAL_PORT}"/>
        </Variable>

        <Variable name="serialConnection" type="TagValueRemoteServerConnection">
            <Param value="serialTransport"/>
            <Param value="serialInitializer"/>
        </Variable>
    </GlobalVariables>

    <SetupFunctions>
        <Function name="addConnection" object="remoteServer">
            <Param ref="serialConnection"/>
        </Function>
    </SetupFunctions>
</TcMenuPlugin>

=== TcMenu/tcMenu/xmlPlugins/core-remote/clientRemoteEthernet.xml
<TcMenuPlugin name="Device client connection to remote server using popular libraries" id="B93C6ACA-F1A3-4FF3-87F1-07E4F2F1ED5A" subsystem="REMOTE"
              requiresDesigner="2.2.0" xmlns="https://www.thecoderscorner.com/libraries/tcmenuPluginItem" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
              xsi:schemaLocation="https://www.thecoderscorner.com/libraries/tcmenuPluginItem https://www.thecoderscorner.com/products/arduino-libraries/libraries/tcmenu-plugin-item.xsd">
    <SupportedPlatforms>
        <Platform>ARDUINO_UNO</Platform>
        <Platform>ARDUINO_AVR</Platform>
        <Platform>ARDUINO_32</Platform>
        <Platform>ARDUINO_ESP8266</Platform>
        <Platform>ARDUINO_ESP32</Platform>
        <Platform>STM32DUINO</Platform>
    </SupportedPlatforms>
    <Description>Control menu remotely where the device acts as a client. The device will attempt to connect to a server at a provided IP address.</Description>
    <Documentation link="https://www.thecoderscorner.com/products/arduino-libraries/tc-menu/tcmenu-iot/ethernet-remote-plugin/"/>
    <RequiredLibraries/>
    <ImageFile>ethernet-shield.jpg</ImageFile>

    <Properties>
        <Property id="ETH_LIBRARY_TYPE" name="Ethernet library type" desc="Choose the library that supports your hardware" initial="ETHERNET_2" type="choice">
            <Choices>
                <Choice desc="Ethernet 2">ETHERNET_2</Choice>
                <Choice desc="UIP Ethernet">UIP_ENC28J60</Choice>
                <Choice desc="STM32Ethernet">STM32ETHERNET</Choice>
                <Choice desc="ESP32 Arduino">ESP32_WIFI</Choice>
                <Choice desc="ESP8266 Arduino">ESP8266_WIFI</Choice>
            </Choices>
        </Property>
        <Property id="REMOTE_IP_ADDRESS" name="IP Address of the server" initial="127.0.0.1" type="text"
                  desc="The IP address of the server to connect to."/>
        <Property id="REMOTE_PORT" name="Remote Port" initial="3333" desc="The port on which the server is listening"
                  type="int" min="0" max="65355"/>
    </Properties>

    <ApplicabilityDefs>
    </ApplicabilityDefs>

    <SourceFiles>
        <Replacement find="Ethernet.h" replace="STM32Ethernet.h" whenProperty="ETH_LIBRARY_TYPE" isValue="STM32ETHERNET"/>
        <Replacement find="Ethernet.h" replace="UIPEthernet.h" whenProperty="ETH_LIBRARY_TYPE" isValue="UIP_ENC28J60"/>
        <Replacement find="Ethernet.h" replace="WiFi.h" whenProperty="ETH_LIBRARY_TYPE" isValue="ESP32_WIFI"/>
        <Replacement find="Ethernet.h" replace="ESP8266WiFi.h" whenProperty="ETH_LIBRARY_TYPE" isValue="ESP8266_WIFI"/>

        <Replacement find="EthernetClient" replace="UIPClient" whenProperty="ETH_LIBRARY_TYPE" isValue="UIP_ENC28J60"/>
        <Replacement find="EthernetServer" replace="UIPServer" whenProperty="ETH_LIBRARY_TYPE" isValue="UIP_ENC28J60"/>

        <Replacement find="EthernetClient" replace="WiFiClient" whenProperty="ETH_LIBRARY_TYPE" matches="ESP.*"/>
        <Replacement find="EthernetServer" replace="WiFiServer" whenProperty="ETH_LIBRARY_TYPE" matches="ESP.*"/>

        <SourceFile name="ethernetSrc/ClientEthernetTransport.cpp"/>
        <SourceFile name="ethernetSrc/ClientEthernetTransport.h"/>
    </SourceFiles>

    <IncludeFiles>
        <Header name="ClientEthernetTransport.h" inSource="true"/>
        <Header name="RemoteConnector.h" inSource="false"/>
    </IncludeFiles>

    <GlobalVariables>
        <Variable name="clientEthInit" type="ClientEthernetInitialisation" export="true">
            <Param value='"${REMOTE_IP_ADDRESS}"' />
            <Param value="${REMOTE_PORT}" />
        </Variable>
        <Variable name="clientEthTransport" type="ClientEthernetTagValTransport" export="true"/>
        <Variable name="clientConnection" type="TagValueRemoteServerConnection" export="false">
            <Param value="clientEthTransport"/>
            <Param value="clientEthInit"/>
        </Variable>

    </GlobalVariables>

    <SetupFunctions>
        <Function name="addConnection" object="remoteServer">
            <Param ref="clientConnection"/>
        </Function>

    </SetupFunctions>
</TcMenuPlugin>
