=== TcMenu/tcMenu/CoreXmlPlugins/tcmenu-plugin-item.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema"
           targetNamespace="https://www.thecoderscorner.com/libraries/tcmenuPluginItem"
           xmlns="https://www.thecoderscorner.com/libraries/tcmenuPluginItem">
  <xs:element name="TcMenuPlugin" type="TcMenuPluginType"/>
  <xs:complexType name="SupportedPlatformsType">
    <xs:sequence>
      <xs:element name="Platform" maxOccurs="unbounded" minOccurs="0">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:enumeration value="ARDUINO_UNO"/>
            <xs:enumeration value="ARDUINO_AVR"/>
            <xs:enumeration value="ARDUINO_32"/>
            <xs:enumeration value="ARDUINO_ESP8266"/>
            <xs:enumeration value="ARDUINO_ESP32"/>
            <xs:enumeration value="ARDUINO_ESP8266"/>
            <xs:enumeration value="MBED_RTOS"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="DocumentationType">
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute type="xs:string" name="link"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
  <xs:complexType name="RequiredLibrariesType">
    <xs:sequence>
      <xs:element name="Library" type="xs:string" maxOccurs="unbounded" minOccurs="0">
      </xs:element>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="PropertyType" mixed="true">
    <xs:sequence>
      <xs:element type="ChoicesType" name="Choices" minOccurs="0"/>
    </xs:sequence>
    <xs:attribute type="xs:string" name="id" use="required"/>
    <xs:attribute type="xs:string" name="name" use="required"/>
    <xs:attribute type="xs:string" name="initial" use="required"/>
    <xs:attribute type="xs:string" name="desc" use="required"/>
    <xs:attribute type="xs:string" name="type" use="required"/>
    <xs:attribute type="xs:string" name="min" use="optional"/>
    <xs:attribute type="xs:string" name="max" use="optional"/>
  </xs:complexType>
  <xs:complexType name="ChoicesType">
    <xs:sequence>
      <xs:element name="Choice" type="xs:string" maxOccurs="unbounded" minOccurs="0">
      </xs:element>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="PropertiesType">
    <xs:sequence>
      <xs:element type="PropertyType" name="Property" maxOccurs="unbounded" minOccurs="0"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="ReplacementType">
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute type="xs:string" name="find" use="required"/>
        <xs:attribute type="xs:string" name="replace" use="required"/>
        <xs:attribute type="xs:string" name="whenProperty" use="optional"/>
        <xs:attribute type="xs:string" name="matches" use="optional"/>
        <xs:attribute type="xs:string" name="isValue" use="optional"/>
        <xs:attribute type="xs:string" name="isNotValue" use="optional"/>
        <xs:attribute type="xs:string" name="applicabilityRef" use="optional"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
  <xs:complexType name="SourceFileType" mixed="true">
    <xs:attribute type="xs:string" name="name" use="required"/>
  </xs:complexType>
  <xs:complexType name="SourceFilesType">
    <xs:sequence>
      <xs:element type="ReplacementType" name="Replacement" maxOccurs="unbounded" minOccurs="0"/>
      <xs:element type="SourceFileType" name="SourceFile" maxOccurs="unbounded" minOccurs="0"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="HeaderType">
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute type="xs:string" name="name" use="required"/>
        <xs:attribute type="xs:string" name="inSource" use="required"/>
        <xs:attribute type="xs:string" name="priority" use="optional"/>
        <xs:attribute type="xs:string" name="matches" use="optional"/>
        <xs:attribute type="xs:string" name="whenProperty" use="optional"/>
        <xs:attribute type="xs:string" name="isValue" use="optional"/>
        <xs:attribute type="xs:string" name="isNotValue" use="optional"/>
        <xs:attribute type="xs:string" name="applicabilityRef" use="optional"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
  <xs:complexType name="IncludeFilesType">
    <xs:sequence>
      <xs:element type="HeaderType" name="Header" maxOccurs="unbounded" minOccurs="0" />
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="ApplicabilityType">
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute type="xs:string" name="matches" use="optional"/>
        <xs:attribute type="xs:string" name="whenProperty" use="optional"/>
        <xs:attribute type="xs:string" name="isValue" use="optional"/>
        <xs:attribute type="xs:string" name="isNotValue" use="optional"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
  <xs:complexType name="ApplicabilityDefType">
    <xs:sequence>
      <xs:element type="ApplicabilityType" name="Applicability" maxOccurs="unbounded" minOccurs="0" />
      <xs:element type="ApplicabilityDefType" name="ApplicabilityDef" minOccurs="0"/>
    </xs:sequence>
    <xs:attribute type="xs:string" name="mode" use="optional"/>
    <xs:attribute type="xs:string" name="key" use="optional"/>
  </xs:complexType>
  <xs:complexType name="ApplicabilityDefsType">
    <xs:sequence>
      <xs:element type="ApplicabilityDefType" name="ApplicabilityDef" maxOccurs="unbounded" minOccurs="0"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="ParamType">
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute type="xs:string" name="value" use="optional"/>
        <xs:attribute type="xs:string" name="default" use="optional"/>
        <xs:attribute type="xs:string" name="type" use="optional"/>
        <xs:attribute type="xs:string" name="name" use="optional"/>
        <xs:attribute type="xs:string" name="used" use="optional"/>
        <xs:attribute type="xs:string" name="ref" use="optional"/>
        <xs:attribute type="xs:string" name="lambda" use="optional"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
  <xs:complexType name="VariableType" mixed="true">
    <xs:sequence>
      <xs:element type="ParamType" name="Param" minOccurs="0" maxOccurs="unbounded"/>
    </xs:sequence>
    <xs:attribute type="xs:string" name="name" use="optional"/>
    <xs:attribute type="xs:string" name="type" use="optional"/>
    <xs:attribute type="xs:string" name="export" use="optional"/>
    <xs:attribute type="xs:string" name="progmem" use="optional"/>
    <xs:attribute type="xs:string" name="matches" use="optional"/>
    <xs:attribute type="xs:string" name="whenProperty" use="optional"/>
    <xs:attribute type="xs:string" name="isValue" use="optional"/>
    <xs:attribute type="xs:string" name="isNotValue" use="optional"/>
    <xs:attribute type="xs:string" name="applicabilityRef" use="optional"/>
  </xs:complexType>
  <xs:complexType name="GlobalVariablesType">
    <xs:sequence>
      <xs:element type="VariableType" name="Variable" maxOccurs="unbounded" minOccurs="0"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="FunctionType">
    <xs:sequence>
      <xs:element type="ParamType" name="Param" maxOccurs="unbounded" minOccurs="0"/>
    </xs:sequence>
    <xs:attribute type="xs:string" name="name" use="optional"/>
    <xs:attribute type="xs:string" name="object" use="optional"/>
    <xs:attribute type="xs:string" name="matches" use="optional"/>
    <xs:attribute type="xs:string" name="whenProperty" use="optional"/>
    <xs:attribute type="xs:string" name="isValue" use="optional"/>
    <xs:attribute type="xs:string" name="isNotValue" use="optional"/>
    <xs:attribute type="xs:string" name="applicabilityRef" use="optional"/>
    <xs:attribute type="xs:string" name="pointer" use="optional"/>
  </xs:complexType>
  <xs:complexType name="LambdaType">
    <xs:sequence>
      <xs:element type="ParamType" name="Param" maxOccurs="unbounded" minOccurs="0"/>
      <xs:element type="FunctionType" name="Function" minOccurs="0" maxOccurs="unbounded"/>
    </xs:sequence>
    <xs:attribute type="xs:string" name="name" use="optional"/>
    <xs:attribute type="xs:string" name="object" use="optional"/>
    <xs:attribute type="xs:string" name="matches" use="optional"/>
    <xs:attribute type="xs:string" name="whenProperty" use="optional"/>
    <xs:attribute type="xs:string" name="isValue" use="optional"/>
    <xs:attribute type="xs:string" name="isNotValue" use="optional"/>
    <xs:attribute type="xs:string" name="applicabilityRef" use="optional"/>
  </xs:complexType>
  <xs:complexType name="SetupFunctionsType">
    <xs:choice maxOccurs="unbounded" minOccurs="0">
      <xs:element type="FunctionType" name="Function" maxOccurs="unbounded" minOccurs="0"/>
      <xs:element type="LambdaType" name="Lambda"/>
    </xs:choice>
  </xs:complexType>
  <xs:complexType name="TcMenuPluginType">
    <xs:sequence>
      <xs:element type="SupportedPlatformsType" name="SupportedPlatforms"/>
      <xs:element type="xs:string" name="Description"/>
      <xs:element type="DocumentationType" name="Documentation"/>
      <xs:element type="RequiredLibrariesType" name="RequiredLibraries"/>
      <xs:element type="xs:string" name="ImageFile"/>
      <xs:element type="PropertiesType" name="Properties"/>
      <xs:element type="ApplicabilityDefsType" name="ApplicabilityDefs"/>
      <xs:element type="SourceFilesType" name="SourceFiles"/>
      <xs:element type="IncludeFilesType" name="IncludeFiles"/>
      <xs:element type="GlobalVariablesType" name="GlobalVariables"/>
      <xs:element type="SetupFunctionsType" name="SetupFunctions"/>
    </xs:sequence>
    <xs:attribute type="xs:string" name="name"/>
    <xs:attribute type="xs:string" name="id"/>
    <xs:attribute type="xs:string" name="subsystem"/>
  </xs:complexType>
</xs:schema>

=== TcMenu/tcMenu/web-designer/tcmenu-xml-plugins/core-remote/simhubConnector.xml
<TcMenuPlugin name="Simhub serial connector" id="4123dfc3-5271-4727-81f0-1a21d06b666b" subsystem="REMOTE"
              xmlns="https://www.thecoderscorner.com/libraries/tcmenuPluginItem" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
              xsi:schemaLocation="https://www.thecoderscorner.com/libraries/tcmenuPluginItem https://www.thecoderscorner.com/arduino-libraries/libraries/tcmenu-plugin-item.xsd">
    <SupportedPlatforms>
        <Platform>ARDUINO_UNO</Platform>
        <Platform>ARDUINO_AVR</Platform>
        <Platform>ARDUINO_32</Platform>
        <Platform>ARDUINO_ESP8266</Platform>
        <Platform>ARDUINO_ESP32</Platform>
        <Platform>STM32DUINO</Platform>
        <Platform>MBED_RTOS</Platform>
    </SupportedPlatforms>
    <Description>Use this option to update menu items from simhub using the custom protocol. The documentation describes how to configure the protocol.</Description>
    <Documentation link="https://www.thecoderscorner.com/products/arduino-libraries/tc-menu/tcmenu-iot/simhub-connector/"/>
    <RequiredLibraries/>
    <ImageFile>simhub.jpg</ImageFile>

    <Properties>
        <Property id="SH_SERIAL_PORT" name="Serial port" desc="Enter the variable name of the serial port, E.G: Serial" initial="Serial" type="variable"/>
        <Property id="STATUS_MENUITEM" name="Connection Status menu item (-1 none)" desc="Optional BooleanMenuItem that shows connection status" initial="-1" type="BooleanMenuItem"/>
    </Properties>

    <ApplicabilityDefs/>

    <SourceFiles>
        <SourceFile name="simhub/SimhubConnector.cpp"/>
        <SourceFile name="simhub/SimhubConnector.h"/>
    </SourceFiles>

    <IncludeFiles>
        <Header name="SimhubConnector.h" inSource="true"/>
    </IncludeFiles>

    <GlobalVariables>
        <Variable  name="simhubConnection" type="SimHubRemoteConnection">
            <Param ref="${SH_SERIAL_PORT}"/>
            <Param value="${STATUS_MENUITEM}"/>
        </Variable>
    </GlobalVariables>

    <SetupFunctions>
        <Function name="addConnection" object="remoteServer">
            <Param ref="simhubConnection"/>
        </Function>
    </SetupFunctions>
</TcMenuPlugin>

=== TcMenu/tcMenu/web-designer/tcmenu-code-generator/src/test/resources/plugins/TestPlugin.xml
<TcMenuPlugin name="Control menu with analog joystick"
              id="20409bb8-b8a1-4d1d-b632-2cf9b57353e3" subsystem="INPUT"
              xmlns="https://www.thecoderscorner.com/libraries/tcmenuPluginItem" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
              xsi:schemaLocation="https://www.thecoderscorner.com/libraries/tcmenuPluginItem https://www.thecoderscorner.com/arduino-libraries/libraries/tcmenu-plugin-item.xsd">

    <SupportedPlatforms>
       <Platform>ARDUINO_UNO</Platform>
       <Platform>ARDUINO_AVR</Platform>
       <Platform>ARDUINO_32</Platform>
    </SupportedPlatforms>
    <Description>Use an analog joystick connected to one of the Arduino inbuilt analog pins along with a switch also connected to an Arduino pin.</Description>
    <Documentation link="https://www.thecoderscorner.com/products/arduino-libraries/tc-menu/tcmenu-plugins/encoder-switches-input-plugin/"/>
    <RequiredLibraries>
        <Library>Library1</Library>
        <Library>Library2</Library>
    </RequiredLibraries>
    <ImageFile>joystick.jpg</ImageFile>

    <Properties>
      <Property id="INT_PROP" name="Int Prop" initial="10" desc="int value" type="int" min="0" max="100"/>
      <Property id="INTERRUPT_SWITCHES" name="Interrupt Switches" initial="false" desc="Enable switches" type="boolean"/>
      <Property id="SWITCH_IODEVICE" name="IoAbstractionRef" initial="" desc="Advanced" type="variable"/>
      <Property id="JOYSTICK_PIN" name="Up Pin" initial="2" desc="button connected" type="pin"/>
      <Property id="TEST_CHOICE" name="Choices" initial="Choice1" desc="Test choices" type="choice">
        <Choices>
          <Choice desc="Choice 1 desc">Choice1</Choice>
          <Choice desc="Choice 2 desc">Choice2</Choice>
        </Choices>
      </Property>
      <Property id="ITEM_FONT" name="Item Font" initial="ada:sans24p7b,1" desc="Item font desc" type="font"/>
      <Property id="IO_EXPANDER" name="Io Expander" initial="devicePins" desc="IO Expander test" type="io-device"/>
    </Properties>
    
    <ApplicabilityDefs>
        <ApplicabilityDef key="applRef" mode="and">
            <Applicability whenProperty="INTERRUPT_SWITCHES" isValue="true"/>
            <ApplicabilityDef mode="or">
                <Applicability whenProperty="INT_PROP" isValue="10"/>
                <ApplicabilityDef mode="and">
                    <Applicability whenProperty="ROOT" isValue="test"/>
                    <Applicability whenProperty="INT_PROP" isValue="20"/>
                </ApplicabilityDef>
            </ApplicabilityDef>
        </ApplicabilityDef>
    </ApplicabilityDefs>
    
    <SourceFiles>
      <Replacement find="someKey" replace="${INT_PROP}"/>
      <Replacement find="otherKey" replace="abc" whenProperty="INTERRUPT_SWITCHES" isValue="true"/>
      <SourceFile name="src/source.h"/>
      <SourceFile name="src/source.cpp"/>
      <SourceFile name="src/extra.cpp" whenProperty="INTERRUPT_SWITCHES" isValue="true"/>
    </SourceFiles>

    <IncludeFiles>
        <Header name="JoystickSwitchInput.h" inSource="false"/>
        <Header name="Scramble.h" inSource="true" priority="high"/>
        <Header name="FontDefInHdr.h" inSource="cpp" whenProperty="INTERRUPT_SWITCHES" isNotValue="false"/>
        <Header name="${ITEM_FONT}" inSource="font" priority="low"/>
        <Header name="source.h" inSource="true" priority="low"/>
    </IncludeFiles>

    <GlobalVariables>
      <Variable name="analogDevice" type="ArduinoAnalogDevice" export="true">
        <Param value="42"/>
      </Variable>
      <Variable name="anotherVar" type="int" export="false" progmem="true" />
      <Variable name="expOnly" type="char[]" export="only" whenProperty="INTERRUPT_SWITCHES" isValue="false"/>
      <Variable name="${ITEM_FONT/.*:([\w_]*),.*/}" type="const GFXfont" export="only" whenProperty="ITEM_FONT" matches="ad[al]:.*"/>
    </GlobalVariables>

    <SetupFunctions>
        <Function name="initialiseInterrupt" object="switches" whenProperty="INTERRUPT_SWITCHES" isValue="true">
            <Param value="${SWITCH_IODEVICE}" default="internalDigitalIo()"/>
            <Param value="${PULLUP_LOGIC"/>
        </Function>
        <Function name="initialise" object="switches" whenProperty="INTERRUPT_SWITCHES" matches="true|false">
            <Param value="${SWITCH_IODEVICE}" default="internalDigitalIo()"/>
            <Param value="${PULLUP_LOGIC}" default="true"/>
            <Param font="${ITEM_FONT}"/>
            <Param ioDevice="${IO_EXPANDER}"/>
        </Function>

        <Lambda name="onReleaseFn">
            <Param type="uint8_t" name="key" used="false"/>
            <Param type="bool" name="held"/>
            <Function name="onMenuSelect" object="menuMgr" applicabilityRef="applRef">
                <Param value="held"/>
            </Function>
            <Function name="anotherFn">
                <Param name="20"/>
            </Function>
        </Lambda>
        <Function name="addSwitch" object="switches">
            <Param value="BUTTON_PIN"/>
            <Param ref="null"/>
        </Function>
        <Function name="onRelease" object="switches">
            <Param value="BUTTON_PIN"/>
            <Param lambda="onReleaseFn"/>
        </Function>
    </SetupFunctions>
</TcMenuPlugin>

=== TcMenu/tcMenu/CoreXmlPlugins/core-display/upDownSwitchesInput.xml
<TcMenuPlugin name="Control menu with UP and DOWN buttons" id="2a3ae3ba-05f4-4c9c-aad3-3ddc88df9049" subsystem="INPUT"
              xmlns="https://www.thecoderscorner.com/libraries/tcmenuPluginItem" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
              xsi:schemaLocation="https://www.thecoderscorner.com/libraries/tcmenuPluginItem https://www.thecoderscorner.com/libraries/tcmenu-plugin-item.xsd">
    <SupportedPlatforms>
       <Platform>ARDUINO_UNO</Platform>
       <Platform>ARDUINO_AVR</Platform>
       <Platform>ARDUINO_32</Platform>
       <Platform>ARDUINO_ESP8266</Platform>
       <Platform>ARDUINO_ESP32</Platform>
       <Platform>MBED_RTOS</Platform>
    </SupportedPlatforms>
    <Description>Switches that represent up, down and OK controlled by switches library. These are fully debounced either pull up or pull down switches and can either be connected direct to Arduino or via an i2c expander.</Description>
    <Documentation link="https://www.thecoderscorner.com/products/arduino-libraries/tc-menu/tcmenu-plugins/encoder-switches-input-plugin/"/>
    <RequiredLibraries/>
    <ImageFile>up-down-encoder.jpg</ImageFile>

    <Properties>
        <Property id="PULLUP_LOGIC" name="PullUp Logic" initial="true" desc="Enable this to use pull up logic, otherwise pull down" type="boolean"/>
        <Property id="INTERRUPT_SWITCHES" name="Interrupt Switches" initial="false" desc="Enable this to use interrupts instead of polling for switches" type="boolean"/>
        <Property id="SWITCH_IODEVICE" name="IoAbstractionRef for Switches" initial="" desc="This allows you to provide an IoAbstractionRef if your input is on an IO expander" type="variable"/>
        <Property id="ENCODER_UP_PIN" name="Up Button Pin" initial="2" desc="The pin on which the UP button is connected" type="pin"/>
        <Property id="ENCODER_DOWN_PIN" name="Down Button Pin" initial="3" desc="The pin on which UP button is connected" type="pin"/>
        <Property id="ENCODER_OK_PIN" name="OK Button Pin" initial="8" desc="The pin on which OK is connected" type="pin"/>
    </Properties>

    <ApplicabilityDefs/>

    <SourceFiles/>

    <IncludeFiles/>

    <GlobalVariables>
        <Variable name="${SWITCH_IODEVICE}" type="IoAbstractionRef" export="only" whenProperty="SWITCH_IODEVICE" isNotValue="" />
    </GlobalVariables>

    <SetupFunctions>
        <Function name="initialiseInterrupt" object="switches" whenProperty="INTERRUPT_SWITCHES" isValue="true">
            <Param value="${SWITCH_IODEVICE}" default="internalDigitalIo()"/>
            <Param value="${PULLUP_LOGIC}"/>
        </Function>
        <Function name="initialise" object="switches" whenProperty="INTERRUPT_SWITCHES" isValue="false">
            <Param value="${SWITCH_IODEVICE}" default="internalDigitalIo()"/>
            <Param value="${PULLUP_LOGIC}"/>
        </Function>

        <Function name="initForUpDownOk" object="menuMgr">
            <Param ref="renderer"/>
            <Param ref="${ROOT}"/>
            <Param value="${ENCODER_UP_PIN}"/>
            <Param value="${ENCODER_DOWN_PIN}"/>
            <Param value="${ENCODER_OK_PIN}"/>
        </Function>
    </SetupFunctions>
</TcMenuPlugin>

=== TcMenu/tcMenu/web-designer/tcmenu-xml-plugins/core-display/analogResistiveTouchScreen.xml
<TcMenuPlugin name="%touch.res.name"
              id="183448ac-a717-4b2b-823d-ffc7c8140ab9" subsystem="INPUT"
              requiresDesigner="2.0"
              xmlns="https://www.thecoderscorner.com/libraries/tcmenuPluginItem" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
              xsi:schemaLocation="https://www.thecoderscorner.com/libraries/tcmenuPluginItem https://www.thecoderscorner.com/arduino-libraries/libraries/tcmenu-plugin-item.xsd">
    <SupportedPlatforms>
        <PlatformGroup>Arduino</PlatformGroup>
        <PlatformGroup>TrueCpp</PlatformGroup>
    </SupportedPlatforms>
    <Description>%touch.res.desc</Description>
    <Documentation link="https://www.thecoderscorner.com/products/arduino-libraries/tc-menu/tcmenu-plugins/resistive-touch-screen-plugin/"/>
    <RequiredLibraries/>
    <ImageFile>resistive-touch.jpg</ImageFile>

    <Properties>
        <Property id="XPLUS_PIN" name="%touch.res.xp" initial="21" desc="%touch.res.xp.desc" type="pin"/>
        <Property id="XMINUS_PIN" name="%touch.res.xn" initial="A0" desc="%touch.res.xn.desc" type="pin"/>
        <Property id="YPLUS_PIN" name="%touch.res.yp" initial="22" desc="%touch.res.yp.desc" type="pin"/>
        <Property id="YMINUS_PIN" name="%touch.res.yn" initial="A1" desc="%touch.res.yn.desc" type="pin"/>

        <Property id="ORIENTATION_SEPARATOR" name="%core.touch.orientation" initial="" desc="%core.touch.orientation.desc" type="separator"/>
        <Property id="LIB_TOUCH_SWAP_XY" name="%core.touch.swap.xy" initial="false" desc="%core.touch.swap.xy.desc" type="boolean" />
        <Property id="LIB_TOUCH_X_INVERTED" name="%core.touch.x.inverted" initial="false" type="boolean" desc="%core.touch.x.inverted.desc"/>
        <Property id="LIB_TOUCH_Y_INVERTED" name="%core.touch.y.inverted" initial="false" type="boolean" desc="%core.touch.y.inverted.desc"/>

        <Property id="CALIB_SEPARATOR" name="%core.touch.calibration" initial="" desc="%core.touch.calibration.desc" type="separator"/>
        <Property id="TOUCH_SCREEN_CALIBRATE" name="%core.enable.touch.calib" initial="true" desc="%core.enable.touch.calib.desc" type="boolean"  />
        <Property id="TOUCH_CALIBRATION_STORAGE_LOC" name="%core.touch.calib.addr" initial="400" type="int" desc="%core.touch.calib.addr.desc"  min="4" max="65535" />
    </Properties>

    <ApplicabilityDefs/>

    <SourceFiles/>

    <IncludeFiles>
        <Header name="graphics/MenuTouchScreenEncoder.h" inSource="false" />
        <Header name="extras/DrawableTouchCalibrator.h" inSource="false" whenProperty="TOUCH_SCREEN_CALIBRATE" isValue="true"/>
    </IncludeFiles>

    <GlobalVariables>
        <Variable name="touchInterrogator" type="iotouch::ResistiveTouchInterrogator" export="true">
            <Param value="${XPLUS_PIN}"/>
            <Param value="${XMINUS_PIN}"/>
            <Param value="${YPLUS_PIN}"/>
            <Param value="${YMINUS_PIN}"/>
        </Variable>

        <Variable name="touchOrientation" type="iotouch::TouchOrientationSettings" export="false">
            <Param value="${LIB_TOUCH_SWAP_XY}"/>
            <Param value="${LIB_TOUCH_X_INVERTED}"/>
            <Param value="${LIB_TOUCH_Y_INVERTED}"/>
        </Variable>

        <Variable name="touchScreen" type="MenuTouchScreenManager" export="true">
            <Param ref="touchInterrogator"/>
            <Param ref="renderer"/>
            <Param value="touchOrientation"/>
        </Variable>

        <Variable name="touchCalibrator" type="tcextras::IoaTouchScreenCalibrator" export="true" whenProperty="TOUCH_SCREEN_CALIBRATE" isValue="true">
            <Param ref="touchScreen"/>
            <Param ref="renderer"/>
            <Param value="${TOUCH_CALIBRATION_STORAGE_LOC}"/>
        </Variable>
    </GlobalVariables>

    <SetupFunctions>
        <Function name="start" object="touchScreen"/>

        <Function name="initWithoutInput" object="menuMgr">
            <Param ref="renderer"/>
            <Param ref="${ROOT}"/>
        </Function>
    </SetupFunctions>
</TcMenuPlugin>

=== TcMenu/tcMenu/web-designer/tcmenu-xml-plugins/core-remote/remoteSerialESP.xml
<TcMenuPlugin name="ESP Serial remote control (Rs232 / USB / Bluetooth)" id="ba23b2a7-040e-40e2-8fae-d45c82cf450b" subsystem="REMOTE"
              xmlns="https://www.thecoderscorner.com/libraries/tcmenuPluginItem" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
              xsi:schemaLocation="https://www.thecoderscorner.com/libraries/tcmenuPluginItem https://www.thecoderscorner.com/arduino-libraries/libraries/tcmenu-plugin-item.xsd">
    <SupportedPlatforms>
        <Platform>ARDUINO_ESP8266</Platform>
        <Platform>ARDUINO_ESP32</Platform>
    </SupportedPlatforms>
    <Description>Use this option to be able to control the menu over many kinds of serial link from ESP boards, for example RS232, USBSerial, Bluetooth. The full menu structure will be available to the remote using either the protocol or the API..</Description>
    <Documentation link="https://www.thecoderscorner.com/products/arduino-libraries/tc-menu/tcmenu-iot/serial-remote-plugin/"/>
    <RequiredLibraries/>
    <ImageFile>serial-connection.jpg</ImageFile>

    <Properties>
        <Property id="SERIAL_PORT" name="Serial port" desc="Enter the variable name of the serial port. E.G: Serial" initial="Serial" type="variable"/>
        <Property id="HARDWARE_PORT" name="Is Hardware Port" desc="The port is a hardware serial port (see HardwareSerial)" initial="true" type="boolean"/>
    </Properties>

    <ApplicabilityDefs/>

    <SourceFiles>
        <Replacement find="Stream&#92;*" replace="HardwareSerial*" whenProperty="HARDWARE_PORT" isValue="true"/>
        <Replacement find="serialPort->availableForWrite() != 0" replace="true" whenProperty="HARDWARE_PORT" isValue="false"/>
        <SourceFile name="serialSrc/SerialTransport.cpp"/>
        <SourceFile name="serialSrc/SerialTransport.h"/>
    </SourceFiles>

    <IncludeFiles>
        <Header name="RemoteConnector.h" inSource="false"/>
        <Header name="SerialTransport.h" inSource="true"/>
    </IncludeFiles>

    <GlobalVariables>
        <Variable name="serialInitializer" type="NoInitialisationNeeded"/>

        <Variable name="serialTransport" type="SerialTagValueTransport">
            <Param ref="${SERIAL_PORT}"/>
        </Variable>

        <Variable name="serialConnection" type="TagValueRemoteServerConnection">
            <Param value="serialTransport"/>
            <Param value="serialInitializer"/>
        </Variable>
    </GlobalVariables>

    <SetupFunctions>
        <Function name="addConnection" object="remoteServer">
            <Param ref="serialConnection"/>
        </Function>
    </SetupFunctions>
</TcMenuPlugin>
