=== TcMenu/tcMenu/CoreXmlPlugins/tcmenu-plugin-item.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema"
           targetNamespace="https://www.thecoderscorner.com/libraries/tcmenuPluginItem"
           xmlns="https://www.thecoderscorner.com/libraries/tcmenuPluginItem">
  <xs:element name="TcMenuPlugin" type="TcMenuPluginType"/>
  <xs:complexType name="SupportedPlatformsType">
    <xs:sequence>
      <xs:element name="Platform" maxOccurs="unbounded" minOccurs="0">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:enumeration value="ARDUINO_UNO"/>
            <xs:enumeration value="ARDUINO_AVR"/>
            <xs:enumeration value="ARDUINO_32"/>
            <xs:enumeration value="ARDUINO_ESP8266"/>
            <xs:enumeration value="ARDUINO_ESP32"/>
            <xs:enumeration value="ARDUINO_ESP8266"/>
            <xs:enumeration value="MBED_RTOS"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="DocumentationType">
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute type="xs:string" name="link"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
  <xs:complexType name="RequiredLibrariesType">
    <xs:sequence>
      <xs:element name="Library" type="xs:string" maxOccurs="unbounded" minOccurs="0">
      </xs:element>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="PropertyType" mixed="true">
    <xs:sequence>
      <xs:element type="ChoicesType" name="Choices" minOccurs="0"/>
    </xs:sequence>
    <xs:attribute type="xs:string" name="id" use="required"/>
    <xs:attribute type="xs:string" name="name" use="required"/>
    <xs:attribute type="xs:string" name="initial" use="required"/>
    <xs:attribute type="xs:string" name="desc" use="required"/>
    <xs:attribute type="xs:string" name="type" use="required"/>
    <xs:attribute type="xs:string" name="min" use="optional"/>
    <xs:attribute type="xs:string" name="max" use="optional"/>
  </xs:complexType>
  <xs:complexType name="ChoicesType">
    <xs:sequence>
      <xs:element name="Choice" type="xs:string" maxOccurs="unbounded" minOccurs="0">
      </xs:element>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="PropertiesType">
    <xs:sequence>
      <xs:element type="PropertyType" name="Property" maxOccurs="unbounded" minOccurs="0"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="ReplacementType">
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute type="xs:string" name="find" use="required"/>
        <xs:attribute type="xs:string" name="replace" use="required"/>
        <xs:attribute type="xs:string" name="whenProperty" use="optional"/>
        <xs:attribute type="xs:string" name="matches" use="optional"/>
        <xs:attribute type="xs:string" name="isValue" use="optional"/>
        <xs:attribute type="xs:string" name="isNotValue" use="optional"/>
        <xs:attribute type="xs:string" name="applicabilityRef" use="optional"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
  <xs:complexType name="SourceFileType" mixed="true">
    <xs:attribute type="xs:string" name="name" use="required"/>
  </xs:complexType>
  <xs:complexType name="SourceFilesType">
    <xs:sequence>
      <xs:element type="ReplacementType" name="Replacement" maxOccurs="unbounded" minOccurs="0"/>
      <xs:element type="SourceFileType" name="SourceFile" maxOccurs="unbounded" minOccurs="0"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="HeaderType">
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute type="xs:string" name="name" use="required"/>
        <xs:attribute type="xs:string" name="inSource" use="required"/>
        <xs:attribute type="xs:string" name="priority" use="optional"/>
        <xs:attribute type="xs:string" name="matches" use="optional"/>
        <xs:attribute type="xs:string" name="whenProperty" use="optional"/>
        <xs:attribute type="xs:string" name="isValue" use="optional"/>
        <xs:attribute type="xs:string" name="isNotValue" use="optional"/>
        <xs:attribute type="xs:string" name="applicabilityRef" use="optional"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
  <xs:complexType name="IncludeFilesType">
    <xs:sequence>
      <xs:element type="HeaderType" name="Header" maxOccurs="unbounded" minOccurs="0" />
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="ApplicabilityType">
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute type="xs:string" name="matches" use="optional"/>
        <xs:attribute type="xs:string" name="whenProperty" use="optional"/>
        <xs:attribute type="xs:string" name="isValue" use="optional"/>
        <xs:attribute type="xs:string" name="isNotValue" use="optional"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
  <xs:complexType name="ApplicabilityDefType">
    <xs:sequence>
      <xs:element type="ApplicabilityType" name="Applicability" maxOccurs="unbounded" minOccurs="0" />
      <xs:element type="ApplicabilityDefType" name="ApplicabilityDef" minOccurs="0"/>
    </xs:sequence>
    <xs:attribute type="xs:string" name="mode" use="optional"/>
    <xs:attribute type="xs:string" name="key" use="optional"/>
  </xs:complexType>
  <xs:complexType name="ApplicabilityDefsType">
    <xs:sequence>
      <xs:element type="ApplicabilityDefType" name="ApplicabilityDef" maxOccurs="unbounded" minOccurs="0"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="ParamType">
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute type="xs:string" name="value" use="optional"/>
        <xs:attribute type="xs:string" name="default" use="optional"/>
        <xs:attribute type="xs:string" name="type" use="optional"/>
        <xs:attribute type="xs:string" name="name" use="optional"/>
        <xs:attribute type="xs:string" name="used" use="optional"/>
        <xs:attribute type="xs:string" name="ref" use="optional"/>
        <xs:attribute type="xs:string" name="lambda" use="optional"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
  <xs:complexType name="VariableType" mixed="true">
    <xs:sequence>
      <xs:element type="ParamType" name="Param" minOccurs="0" maxOccurs="unbounded"/>
    </xs:sequence>
    <xs:attribute type="xs:string" name="name" use="optional"/>
    <xs:attribute type="xs:string" name="type" use="optional"/>
    <xs:attribute type="xs:string" name="export" use="optional"/>
    <xs:attribute type="xs:string" name="progmem" use="optional"/>
    <xs:attribute type="xs:string" name="matches" use="optional"/>
    <xs:attribute type="xs:string" name="whenProperty" use="optional"/>
    <xs:attribute type="xs:string" name="isValue" use="optional"/>
    <xs:attribute type="xs:string" name="isNotValue" use="optional"/>
    <xs:attribute type="xs:string" name="applicabilityRef" use="optional"/>
  </xs:complexType>
  <xs:complexType name="GlobalVariablesType">
    <xs:sequence>
      <xs:element type="VariableType" name="Variable" maxOccurs="unbounded" minOccurs="0"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="FunctionType">
    <xs:sequence>
      <xs:element type="ParamType" name="Param" maxOccurs="unbounded" minOccurs="0"/>
    </xs:sequence>
    <xs:attribute type="xs:string" name="name" use="optional"/>
    <xs:attribute type="xs:string" name="object" use="optional"/>
    <xs:attribute type="xs:string" name="matches" use="optional"/>
    <xs:attribute type="xs:string" name="whenProperty" use="optional"/>
    <xs:attribute type="xs:string" name="isValue" use="optional"/>
    <xs:attribute type="xs:string" name="isNotValue" use="optional"/>
    <xs:attribute type="xs:string" name="applicabilityRef" use="optional"/>
    <xs:attribute type="xs:string" name="pointer" use="optional"/>
  </xs:complexType>
  <xs:complexType name="LambdaType">
    <xs:sequence>
      <xs:element type="ParamType" name="Param" maxOccurs="unbounded" minOccurs="0"/>
      <xs:element type="FunctionType" name="Function" minOccurs="0" maxOccurs="unbounded"/>
    </xs:sequence>
    <xs:attribute type="xs:string" name="name" use="optional"/>
    <xs:attribute type="xs:string" name="object" use="optional"/>
    <xs:attribute type="xs:string" name="matches" use="optional"/>
    <xs:attribute type="xs:string" name="whenProperty" use="optional"/>
    <xs:attribute type="xs:string" name="isValue" use="optional"/>
    <xs:attribute type="xs:string" name="isNotValue" use="optional"/>
    <xs:attribute type="xs:string" name="applicabilityRef" use="optional"/>
  </xs:complexType>
  <xs:complexType name="SetupFunctionsType">
    <xs:choice maxOccurs="unbounded" minOccurs="0">
      <xs:element type="FunctionType" name="Function" maxOccurs="unbounded" minOccurs="0"/>
      <xs:element type="LambdaType" name="Lambda"/>
    </xs:choice>
  </xs:complexType>
  <xs:complexType name="TcMenuPluginType">
    <xs:sequence>
      <xs:element type="SupportedPlatformsType" name="SupportedPlatforms"/>
      <xs:element type="xs:string" name="Description"/>
      <xs:element type="DocumentationType" name="Documentation"/>
      <xs:element type="RequiredLibrariesType" name="RequiredLibraries"/>
      <xs:element type="xs:string" name="ImageFile"/>
      <xs:element type="PropertiesType" name="Properties"/>
      <xs:element type="ApplicabilityDefsType" name="ApplicabilityDefs"/>
      <xs:element type="SourceFilesType" name="SourceFiles"/>
      <xs:element type="IncludeFilesType" name="IncludeFiles"/>
      <xs:element type="GlobalVariablesType" name="GlobalVariables"/>
      <xs:element type="SetupFunctionsType" name="SetupFunctions"/>
    </xs:sequence>
    <xs:attribute type="xs:string" name="name"/>
    <xs:attribute type="xs:string" name="id"/>
    <xs:attribute type="xs:string" name="subsystem"/>
  </xs:complexType>
</xs:schema>

=== TcMenu/tcMenu/web-designer/tcmenu-xml-plugins/core-display/liquidCrystalDisplay.xml
<TcMenuPlugin name="LCD shield renderer for any configuration"
              id="61f370f4-0294-41cf-8988-1458f242914a" subsystem="DISPLAY"
              requiresDesigner="2.2"
              xmlns="https://www.thecoderscorner.com/libraries/tcmenuPluginItem" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
              xsi:schemaLocation="https://www.thecoderscorner.com/libraries/tcmenuPluginItem https://www.thecoderscorner.com/arduino-libraries/libraries/tcmenu-plugin-item.xsd">
    <SupportedPlatforms>
        <PlatformGroup>Arduino</PlatformGroup>
        <PlatformGroup>TrueCpp</PlatformGroup>
    </SupportedPlatforms>
    <Description>LiquidCrystal based display driver that can be configured to work with any pin arrangement. Just set the EN, RS, Data pins at a minimum. It also has optional inbuilt backlight and PWM contrast support.</Description>
    <Documentation link="https://www.thecoderscorner.com/products/arduino-libraries/tc-menu/tcmenu-plugins/liquidcrystalio-hd44780-renderer-plugin/"/>
    <RequiredLibraries/>
    <ImageFile>lcd-display.jpg</ImageFile>

    <Properties>
        <Property id="LCD_WIDTH" name="%lcd.char.width" initial="16" desc="%lcd.char.width.desc" type="int" min="1" max="20"/>
        <Property id="LCD_HEIGHT" name="%lcd.char.height" initial="2" desc="%lcd.char.height.desc" type="int" min="1" max="4"/>
        <Property id="LCD_RS" name="LCD RS Pin" initial="1" desc="RS Pin connection to LCD" type="pin"/>
        <Property id="LCD_RW" name="LCD RW Pin" initial="-1" desc="RW Pin connection to LCD" type="pin"/>
        <Property id="LCD_EN" name="LCD EN Pin" initial="2" desc="EN Pin connection to LCD" type="pin"/>
        <Property id="LCD_D4" name="LCD D4 Pin" initial="4" desc="D4 Pin connection to LCD" type="pin"/>
        <Property id="LCD_D5" name="LCD D5 Pin" initial="5" desc="D5 Pin connection to LCD" type="pin"/>
        <Property id="LCD_D6" name="LCD D6 Pin" initial="6" desc="D6 Pin connection to LCD" type="pin"/>
        <Property id="LCD_D7" name="LCD D7 Pin" initial="7" desc="D7 Pin connection to LCD" type="pin"/>
        <Property id="LCD_BACKLIGHT" name="%lcd.backlight.pin" initial="-1" desc="%lcd.backlight.pin.desc" type="pin"/>
        <Property id="LCD_PWM_PIN" name="%lcd.pwm.contrast.pin" initial="-1" desc="%lcd.pwm.contrast.pin.desc" type="pin"/>
        <Property id="LCD_IO_DEVICE" name="%lcd.io.device" initial="devicePins" desc="%lcd.io.device.desc" type="io-device"/>
        <Property id="UNO_OR_FULL" name="%dfrobot.uno.full" initial="unoLcd" desc="%dfrobot.uno.full.desc" type="choice">
            <Choices>
                <Choice desc="Uno - Low Memory">unoLcd</Choice>
                <Choice desc="Full - More Configurable">fullLcd</Choice>
            </Choices>
        </Property>
        <Property id="UPDATES_PER_SEC" name="%core.screen.updates.sec" initial="2" desc="%core.screen.updates.sec.desc" type="int" min="1" max="10"/>
    </Properties>

    <ApplicabilityDefs/>

    <SourceFiles>
        <SourceFile name="${UNO_OR_FULL}/tcMenuLiquidCrystal.cpp" />
        <SourceFile name="${UNO_OR_FULL}/tcMenuLiquidCrystal.h" />
    </SourceFiles>

    <IncludeFiles>
        <Header name="LiquidCrystalIO.h" inSource="false"/>
        <Header name="tcMenuLiquidCrystal.h" inSource="true" priority="low"/>
    </IncludeFiles>

    <GlobalVariables>
        <Variable name="lcd" type="LiquidCrystal" export="true" progmem="false">
            <Param value="${LCD_RS}"/>
            <Param value="${LCD_RW}"/>
            <Param value="${LCD_EN}"/>
            <Param value="${LCD_D4}"/>
            <Param value="${LCD_D5}"/>
            <Param value="${LCD_D6}"/>
            <Param value="${LCD_D7}"/>
        </Variable>

        <Variable name="renderer" type="LiquidCrystalRenderer" export="true" progmem="false">
            <Param value="lcd"/>
            <Param value="${LCD_WIDTH}"/>
            <Param value="${LCD_HEIGHT}"/>
        </Variable>
    </GlobalVariables>

    <SetupFunctions>
        <Function name="setIoAbstraction" object="lcd">
            <Param ioDevice="${LCD_IO_DEVICE}"/>
        </Function>

        <Function name="begin" object="lcd">
            <Param value="${LCD_WIDTH}"/>
            <Param value="${LCD_HEIGHT}"/>
        </Function>

        <Function object="renderer" name="setUpdatesPerSecond">
            <Param value="${UPDATES_PER_SEC}"/>
        </Function>

        <Function name="configureBacklightPin" object="lcd" whenProperty="LCD_BACKLIGHT" isNotValue="-1">
            <Param value="${LCD_BACKLIGHT}"/>
        </Function>
        <Function name="backlight" object="lcd" whenProperty="LCD_BACKLIGHT" isNotValue="-1"/>

        <Function name="pinMode" whenProperty="LCD_PWM_PIN" isNotValue="-1">
            <Param value="${LCD_PWM_PIN}"/>
            <Param value="INPUT"/>
        </Function>
        <Function name="analogWrite" whenProperty="LCD_PWM_PIN" isNotValue="-1">
            <Param value="${LCD_PWM_PIN}"/>
            <Param value="10"/>
        </Function>
    </SetupFunctions>
</TcMenuPlugin>

=== TcMenu/tcMenu/tcMenuGenerator/src/test/resources/plugins/TestPluginVersionAllowed.xml
<TcMenuPlugin name="Plugin designer version OK"
              id="20409bb8-b8a1-4d1d-b632-2cf9b5739888" subsystem="INPUT"
              requiresDesigner="1.3"
              xmlns="https://www.thecoderscorner.com/libraries/tcmenuPluginItem" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
              xsi:schemaLocation="https://www.thecoderscorner.com/libraries/tcmenuPluginItem https://www.thecoderscorner.com/libraries/tcmenu-plugin-item.xsd">

    <SupportedPlatforms>
       <Platform>ARDUINO_UNO</Platform>
       <Platform>ARDUINO_AVR</Platform>
       <Platform>ARDUINO_32</Platform>
    </SupportedPlatforms>
    <Description>Plugin is allowed because required version is met.</Description>
    <Documentation link="https://www.thecoderscorner.com/products/arduino-libraries/tc-menu/tcmenu-plugins/encoder-switches-input-plugin/"/>
    <RequiredLibraries>
        <Library>Library1</Library>
    </RequiredLibraries>
    <ImageFile>joystick.jpg</ImageFile>

    <Properties>
      <Property id="INT_PROP" name="Int Prop" initial="10" desc="int value" type="int" min="0" max="100"/>
    </Properties>
    
    <ApplicabilityDefs/>

    <SourceFiles/>

    <IncludeFiles>
        <Header name="Scramble.h" inSource="true" priority="high"/>
    </IncludeFiles>

    <GlobalVariables>
      <Variable name="allowedPluginVar" type="int" export="false" progmem="true" />
    </GlobalVariables>

    <SetupFunctions/>
</TcMenuPlugin>

=== TcMenu/tcMenu/CoreXmlPlugins/core-display/liquidCrystalDisplay.xml
<TcMenuPlugin name="LCD shield renderer for any configuration" id="61f370f4-0294-41cf-8988-1458f242914a" subsystem="DISPLAY"
              xmlns="https://www.thecoderscorner.com/libraries/tcmenuPluginItem" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
              xsi:schemaLocation="https://www.thecoderscorner.com/libraries/tcmenuPluginItem https://www.thecoderscorner.com/libraries/tcmenu-plugin-item.xsd">
    <SupportedPlatforms>
       <Platform>ARDUINO_UNO</Platform>
       <Platform>ARDUINO_AVR</Platform>
       <Platform>ARDUINO_32</Platform>
       <Platform>ARDUINO_ESP8266</Platform>
       <Platform>ARDUINO_ESP32</Platform>
       <Platform>MBED_RTOS</Platform>
    </SupportedPlatforms>
    <Description>LiquidCrystal based display driver that can be configured to work with any pin arrangement. Just set the EN, RS, Data pins at a minimum. It also has optional inbuilt backlight and PWM contrast support.</Description>
    <Documentation link="https://www.thecoderscorner.com/products/arduino-libraries/tc-menu/tcmenu-plugins/liquidcrystalio-hd44780-renderer-plugin/"/>
    <RequiredLibraries/>
    <ImageFile>lcd-display.jpg</ImageFile>

    <Properties>
        <Property id="LCD_WIDTH" name="Lcd Width" initial="16" desc="Number of characters across the LCD" type="int" min="1" max="20"/>
        <Property id="LCD_HEIGHT" name="Lcd Height" initial="2" desc="Number of rows on the LCD" type="int" min="1" max="4"/>
        <Property id="LCD_EN" name="LCD EN Pin" initial="2" desc="EN Pin connection to LCD" type="pin"/>
        <Property id="LCD_RS" name="LCD RS Pin" initial="1" desc="RS Pin connection to LCD" type="pin"/>
        <Property id="LCD_D4" name="LCD D4 Pin" initial="4" desc="D4 Pin connection to LCD" type="pin"/>
        <Property id="LCD_D5" name="LCD D5 Pin" initial="5" desc="D5 Pin connection to LCD" type="pin"/>
        <Property id="LCD_D6" name="LCD D6 Pin" initial="6" desc="D6 Pin connection to LCD" type="pin"/>
        <Property id="LCD_D7" name="LCD D7 Pin" initial="7" desc="D7 Pin connection to LCD" type="pin"/>
        <Property id="LCD_BACKLIGHT" name="Backlight Pin" initial="-1" desc="Optional backlight pin, -1 for none" type="pin"/>
        <Property id="LCD_PWM_PIN" name="PWM Contrast Pin" initial="-1" desc="Optional PWM contrast pin, -1 for none" type="pin"/>
        <Property id="LCD_IO_DEVICE" name="LCD IO Device (default blank)" initial="" desc="This allows you to provide an IoAbstractionRef if your display is on a non-standard IO expander" type="variable"/>
    </Properties>

    <ApplicabilityDefs/>

    <SourceFiles>
        <SourceFile name="lcdSrc/tcMenuLiquidCrystal.cpp" />
        <SourceFile name="lcdSrc/tcMenuLiquidCrystal.h" />
    </SourceFiles>

    <IncludeFiles>
        <Header name="LiquidCrystalIO.h" inSource="false"/>
        <Header name="tcMenuLiquidCrystal.h" inSource="true" priority="low"/>
    </IncludeFiles>

    <GlobalVariables>
        <Variable name="${LCD_IO_DEVICE}" type="IoAbstractionRef" export="only" whenProperty="LCD_IO_DEVICE" isNotValue="" />

        <Variable name="lcd" type="LiquidCrystal" export="true" progmem="false">
            <Param value="${LCD_RS}"/>
            <Param value="${LCD_EN}"/>
            <Param value="${LCD_D4}"/>
            <Param value="${LCD_D5}"/>
            <Param value="${LCD_D6}"/>
            <Param value="${LCD_D7}"/>
        </Variable>

        <Variable name="renderer" type="LiquidCrystalRenderer" export="true" progmem="false">
            <Param value="lcd"/>
            <Param value="${LCD_WIDTH}"/>
            <Param value="${LCD_HEIGHT}"/>
        </Variable>
    </GlobalVariables>

    <SetupFunctions>
        <Function name="setIoAbstraction" object="lcd">
            <Param value="${LCD_IO_DEVICE}" default="internalDigitalIo()"/>
        </Function>

        <Function name="begin" object="lcd">
            <Param value="${LCD_WIDTH}"/>
            <Param value="${LCD_HEIGHT}"/>
        </Function>

        <Function name="configureBacklightPin" object="lcd" whenProperty="LCD_BACKLIGHT" isNotValue="-1">
            <Param value="${LCD_BACKLIGHT}"/>
        </Function>
        <Function name="backlight" object="lcd" whenProperty="LCD_BACKLIGHT" isNotValue="-1"/>

        <Function name="pinMode" whenProperty="LCD_PWM_PIN" isNotValue="-1">
            <Param value="${LCD_PWM_PIN}"/>
            <Param value="INPUT"/>
        </Function>
        <Function name="analogWrite" whenProperty="LCD_PWM_PIN" isNotValue="-1">
            <Param value="${LCD_PWM_PIN}"/>
            <Param value="10"/>
        </Function>
    </SetupFunctions>
</TcMenuPlugin>

=== TcMenu/tcMenu/web-designer/tcmenu-xml-plugins/core-display/esp32TouchSensor.xml
<TcMenuPlugin name="%esp32.sensor.name"
              id="cc0f9246-03be-4adf-b1f5-dd501085122a" subsystem="INPUT"
              requiresDesigner="2.0"
              xmlns="https://www.thecoderscorner.com/libraries/tcmenuPluginItem" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
              xsi:schemaLocation="https://www.thecoderscorner.com/libraries/tcmenuPluginItem https://www.thecoderscorner.com/arduino-libraries/libraries/tcmenu-plugin-item.xsd">
    <SupportedPlatforms>
           <Platform>ARDUINO_ESP32</Platform>
    </SupportedPlatforms>
    <Description>%esp32.sensor.desc</Description>
    <Documentation link="https://www.thecoderscorner.com/products/arduino-libraries/tc-menu/tcmenu-plugins/touch-pad-sensor-plugin/"/>
    <RequiredLibraries/>
    <ImageFile>touch-pad-sensor.jpg</ImageFile>

    <Properties>
        <Property id="SWITCH_THRESHOLD" name="%esp32.sensor.threshold" initial="800" desc="%esp32.sensor.threshold.desc" type="int" min="0" max="32768"/>
        <Property id="SW_POLLING_MODE" name="%core.input.polling" initial="SWITCHES_POLL_EVERYTHING" desc="%core.input.polling.desc" type="choice">
            <Choices>
                <Choice desc="%core.input.polling.all">SWITCHES_POLL_EVERYTHING</Choice>
                <Choice desc="%core.input.polling.none">SWITCHES_NO_POLLING</Choice>
                <Choice desc="%core.input.polling.keys">SWITCHES_POLL_KEYS_ONLY</Choice>
            </Choices>
        </Property>
        <Property id="TP_HIGH_VOLTAGE" name="%esp32.sensor.high.voltage" initial="TOUCH_HVOLT_2V7" desc="%esp32.sensor.high.voltage.desc" type="choice">
            <Choices>
                <Choice>TOUCH_HVOLT_KEEP</Choice>
                <Choice>TOUCH_HVOLT_2V4</Choice>
                <Choice>TOUCH_HVOLT_2V5</Choice>
                <Choice>TOUCH_HVOLT_2V6</Choice>
                <Choice>TOUCH_HVOLT_2V7</Choice>
                <Choice>TOUCH_HVOLT_MAX</Choice>
            </Choices>
        </Property>
        <Property id="TP_LOW_VOLTAGE" name="%esp32.sensor.low.voltage" initial="TOUCH_LVOLT_0V5" desc="%esp32.sensor.low.voltage.desc" type="choice">
            <Choices>
                <Choice>TOUCH_LVOLT_KEEP</Choice>
                <Choice>TOUCH_LVOLT_0V5</Choice>
                <Choice>TOUCH_LVOLT_0V6</Choice>
                <Choice>TOUCH_LVOLT_0V7</Choice>
                <Choice>TOUCH_LVOLT_0V8</Choice>
                <Choice>TOUCH_LVOLT_MAX</Choice>
            </Choices>
        </Property>
        <Property id="TP_ATTENUATION" name="%esp32.sensor.attenuation" initial="TOUCH_HVOLT_ATTEN_1V" desc="%esp32.sensor.attenuation.desc" type="choice">
            <Choices>
                <Choice>TOUCH_HVOLT_ATTEN_KEEP</Choice>
                <Choice>TOUCH_HVOLT_ATTEN_1V5</Choice>
                <Choice>TOUCH_HVOLT_ATTEN_1V</Choice>
                <Choice>TOUCH_HVOLT_ATTEN_0V5</Choice>
                <Choice>TOUCH_HVOLT_ATTEN_0V</Choice>
                <Choice>TOUCH_HVOLT_ATTEN_MAX</Choice>
            </Choices>
        </Property>
        <Property id="TP_THRESHOLD_DETECTION" name="%esp32.sensor.threshold.mode" initial="TOUCH_TRIGGER_BELOW" desc="%esp32.sensor.threshold.mode.desc" type="choice">
            <Choices>
                <Choice desc="Triggers BELOW threshold">TOUCH_TRIGGER_BELOW</Choice>
                <Choice desc="Triggers ABOVE threshold">TOUCH_TRIGGER_ABOVE</Choice>
            </Choices>
        </Property>
        <Property id="UP_SENSOR" name="%esp32.sensor.up" initial="3" desc="%esp32.sensor.up.desc" type="pin"/>
        <Property id="DOWN_SENSOR" name="%esp32.sensor.down" initial="3" desc="%esp32.sensor.down.desc" type="pin"/>
        <Property id="BACK_SENSOR" name="%esp32.sensor.left" initial="-1" desc="%esp32.sensor.left.desc" type="pin"/>
        <Property id="NEXT_SENSOR" name="%esp32.sensor.right" initial="-1" desc="%esp32.sensor.right.desc" type="pin"/>
        <Property id="SELECT_SENSOR" name="%esp32.sensor.sel" initial="3" desc="%esp32.sensor.sel.desc" type="pin"/>
        <Property id="TS_KEY_REPEAT" name="%core.key.repeat.speed" initial="20" desc="%core.key.repeat.speed.desc"
                  type="int" min="1" max="50"/>
    </Properties>

    <ApplicabilityDefs>
        <ApplicabilityDef key="leftAndRightDefined" mode="and">
            <Applicability whenProperty="BACK_SENSOR" isNotValue="-1"/>
            <Applicability whenProperty="NEXT_SENSOR" isNotValue="-1"/>
        </ApplicabilityDef>
        <ApplicabilityDef key="leftAndRightNotDefined" mode="and">
            <Applicability whenProperty="BACK_SENSOR" isValue="-1"/>
            <Applicability whenProperty="NEXT_SENSOR" isValue="-1"/>
        </ApplicabilityDef>
    </ApplicabilityDefs>

    <SourceFiles>
    </SourceFiles>

    <IncludeFiles>
        <Header name="esp32/ESP32TouchKeysAbstraction.h" inSource="false"/>
    </IncludeFiles>

    <GlobalVariables>
        <Variable name="esp32Touch" type="ESP32TouchKeysAbstraction" export="true">
            <Param value="${SWITCH_THRESHOLD}"/>
            <Param value="${TP_HIGH_VOLTAGE}"/>
            <Param value="${TP_LOW_VOLTAGE}"/>
            <Param value="${TP_ATTENUATION}"/>
        </Variable>
    </GlobalVariables>

    <SetupFunctions>
        <Function name="setTouchTriggerMode" object="esp32Touch">
            <Param value="${TP_THRESHOLD_DETECTION}"/>
        </Function>

        <Function name="init" object="switches">
            <Param ref="esp32Touch" />
            <Param value="${SW_POLLING_MODE}" />
            <Param value="false"/>
        </Function>

        <Function name="initForUpDownOk" object="menuMgr" applicabilityRef="leftAndRightNotDefined">
            <Param ref="renderer"/>
            <Param ref="${ROOT}"/>
            <Param value="${DOWN_SENSOR}"/>
            <Param value="${UP_SENSOR}"/>
            <Param value="${SELECT_SENSOR}"/>
            <Param value="${TS_KEY_REPEAT}"/>
        </Function>

        <Function name="initFor4WayJoystick" object="menuMgr" applicabilityRef="leftAndRightDefined">
            <Param ref="renderer"/>
            <Param ref="${ROOT}"/>
            <Param value="${DOWN_SENSOR}"/>
            <Param value="${UP_SENSOR}"/>
            <Param value="${BACK_SENSOR}"/>
            <Param value="${NEXT_SENSOR}"/>
            <Param value="${SELECT_SENSOR}"/>
            <Param value="${TS_KEY_REPEAT}"/>
        </Function>

        <Function name="ensureInterruptRegistered" object="esp32Touch"/>
    </SetupFunctions>
</TcMenuPlugin>

=== TcMenu/tcMenu/web-designer/tcmenu-code-generator/src/test/resources/plugins/test-theme-item-plugin.xml
<TcMenuPlugin name="Unit test theme plugin" id="0BB96E3C-192F-4A29-97E1-A5004E9816F7"
              subsystem="THEME" requiresDesigner="2.0"
              xmlns="https://www.thecoderscorner.com/libraries/tcmenuPluginItem" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
              xsi:schemaLocation="https://www.thecoderscorner.com/libraries/tcmenuPluginItem https://www.thecoderscorner.com/arduino-libraries/libraries/tcmenu-plugin-item.xsd">
    <SupportedPlatforms>
        <Platform>ARDUINO_UNO</Platform>
        <Platform>ARDUINO_AVR</Platform>
        <Platform>ARDUINO_32</Platform>
        <Platform>ARDUINO_ESP8266</Platform>
        <Platform>ARDUINO_ESP32</Platform>
        <Platform>MBED_RTOS</Platform>
    </SupportedPlatforms>
    <Description>Unit test plugin for Themes, not intended for production use.</Description>
    <Documentation link="https://www.thecoderscorner.com/products/arduino-libraries/tc-menu/rendering-with-tcmenu-LCD-TFT-OLED/"/>
    <RequiredLibraries/>
    <ImageFile>joystick.jpg</ImageFile>

    <Properties>
        <Property id="THEME_ITEM1" name="ThemeProperty1" initial="1234" desc="ThemeProperty1" type="int"/>
    </Properties>

    <ApplicabilityDefs/>

    <SourceFiles/>

    <IncludeFiles>
        <Header name="superTheme123.h" inSource="cppsrc"/>
    </IncludeFiles>

    <GlobalVariables/>

    <SetupFunctions>
        <Function name="initialiseMyTheme">
            <Param value="${THEME_ITEM_1}"/>
        </Function>
    </SetupFunctions>

</TcMenuPlugin>
