=== TcMenu/tcMenu/CoreXmlPlugins/tcmenu-plugin-item.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema"
           targetNamespace="https://www.thecoderscorner.com/libraries/tcmenuPluginItem"
           xmlns="https://www.thecoderscorner.com/libraries/tcmenuPluginItem">
  <xs:element name="TcMenuPlugin" type="TcMenuPluginType"/>
  <xs:complexType name="SupportedPlatformsType">
    <xs:sequence>
      <xs:element name="Platform" maxOccurs="unbounded" minOccurs="0">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:enumeration value="ARDUINO_UNO"/>
            <xs:enumeration value="ARDUINO_AVR"/>
            <xs:enumeration value="ARDUINO_32"/>
            <xs:enumeration value="ARDUINO_ESP8266"/>
            <xs:enumeration value="ARDUINO_ESP32"/>
            <xs:enumeration value="ARDUINO_ESP8266"/>
            <xs:enumeration value="MBED_RTOS"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="DocumentationType">
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute type="xs:string" name="link"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
  <xs:complexType name="RequiredLibrariesType">
    <xs:sequence>
      <xs:element name="Library" type="xs:string" maxOccurs="unbounded" minOccurs="0">
      </xs:element>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="PropertyType" mixed="true">
    <xs:sequence>
      <xs:element type="ChoicesType" name="Choices" minOccurs="0"/>
    </xs:sequence>
    <xs:attribute type="xs:string" name="id" use="required"/>
    <xs:attribute type="xs:string" name="name" use="required"/>
    <xs:attribute type="xs:string" name="initial" use="required"/>
    <xs:attribute type="xs:string" name="desc" use="required"/>
    <xs:attribute type="xs:string" name="type" use="required"/>
    <xs:attribute type="xs:string" name="min" use="optional"/>
    <xs:attribute type="xs:string" name="max" use="optional"/>
  </xs:complexType>
  <xs:complexType name="ChoicesType">
    <xs:sequence>
      <xs:element name="Choice" type="xs:string" maxOccurs="unbounded" minOccurs="0">
      </xs:element>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="PropertiesType">
    <xs:sequence>
      <xs:element type="PropertyType" name="Property" maxOccurs="unbounded" minOccurs="0"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="ReplacementType">
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute type="xs:string" name="find" use="required"/>
        <xs:attribute type="xs:string" name="replace" use="required"/>
        <xs:attribute type="xs:string" name="whenProperty" use="optional"/>
        <xs:attribute type="xs:string" name="matches" use="optional"/>
        <xs:attribute type="xs:string" name="isValue" use="optional"/>
        <xs:attribute type="xs:string" name="isNotValue" use="optional"/>
        <xs:attribute type="xs:string" name="applicabilityRef" use="optional"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
  <xs:complexType name="SourceFileType" mixed="true">
    <xs:attribute type="xs:string" name="name" use="required"/>
  </xs:complexType>
  <xs:complexType name="SourceFilesType">
    <xs:sequence>
      <xs:element type="ReplacementType" name="Replacement" maxOccurs="unbounded" minOccurs="0"/>
      <xs:element type="SourceFileType" name="SourceFile" maxOccurs="unbounded" minOccurs="0"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="HeaderType">
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute type="xs:string" name="name" use="required"/>
        <xs:attribute type="xs:string" name="inSource" use="required"/>
        <xs:attribute type="xs:string" name="priority" use="optional"/>
        <xs:attribute type="xs:string" name="matches" use="optional"/>
        <xs:attribute type="xs:string" name="whenProperty" use="optional"/>
        <xs:attribute type="xs:string" name="isValue" use="optional"/>
        <xs:attribute type="xs:string" name="isNotValue" use="optional"/>
        <xs:attribute type="xs:string" name="applicabilityRef" use="optional"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
  <xs:complexType name="IncludeFilesType">
    <xs:sequence>
      <xs:element type="HeaderType" name="Header" maxOccurs="unbounded" minOccurs="0" />
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="ApplicabilityType">
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute type="xs:string" name="matches" use="optional"/>
        <xs:attribute type="xs:string" name="whenProperty" use="optional"/>
        <xs:attribute type="xs:string" name="isValue" use="optional"/>
        <xs:attribute type="xs:string" name="isNotValue" use="optional"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
  <xs:complexType name="ApplicabilityDefType">
    <xs:sequence>
      <xs:element type="ApplicabilityType" name="Applicability" maxOccurs="unbounded" minOccurs="0" />
      <xs:element type="ApplicabilityDefType" name="ApplicabilityDef" minOccurs="0"/>
    </xs:sequence>
    <xs:attribute type="xs:string" name="mode" use="optional"/>
    <xs:attribute type="xs:string" name="key" use="optional"/>
  </xs:complexType>
  <xs:complexType name="ApplicabilityDefsType">
    <xs:sequence>
      <xs:element type="ApplicabilityDefType" name="ApplicabilityDef" maxOccurs="unbounded" minOccurs="0"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="ParamType">
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute type="xs:string" name="value" use="optional"/>
        <xs:attribute type="xs:string" name="default" use="optional"/>
        <xs:attribute type="xs:string" name="type" use="optional"/>
        <xs:attribute type="xs:string" name="name" use="optional"/>
        <xs:attribute type="xs:string" name="used" use="optional"/>
        <xs:attribute type="xs:string" name="ref" use="optional"/>
        <xs:attribute type="xs:string" name="lambda" use="optional"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
  <xs:complexType name="VariableType" mixed="true">
    <xs:sequence>
      <xs:element type="ParamType" name="Param" minOccurs="0" maxOccurs="unbounded"/>
    </xs:sequence>
    <xs:attribute type="xs:string" name="name" use="optional"/>
    <xs:attribute type="xs:string" name="type" use="optional"/>
    <xs:attribute type="xs:string" name="export" use="optional"/>
    <xs:attribute type="xs:string" name="progmem" use="optional"/>
    <xs:attribute type="xs:string" name="matches" use="optional"/>
    <xs:attribute type="xs:string" name="whenProperty" use="optional"/>
    <xs:attribute type="xs:string" name="isValue" use="optional"/>
    <xs:attribute type="xs:string" name="isNotValue" use="optional"/>
    <xs:attribute type="xs:string" name="applicabilityRef" use="optional"/>
  </xs:complexType>
  <xs:complexType name="GlobalVariablesType">
    <xs:sequence>
      <xs:element type="VariableType" name="Variable" maxOccurs="unbounded" minOccurs="0"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="FunctionType">
    <xs:sequence>
      <xs:element type="ParamType" name="Param" maxOccurs="unbounded" minOccurs="0"/>
    </xs:sequence>
    <xs:attribute type="xs:string" name="name" use="optional"/>
    <xs:attribute type="xs:string" name="object" use="optional"/>
    <xs:attribute type="xs:string" name="matches" use="optional"/>
    <xs:attribute type="xs:string" name="whenProperty" use="optional"/>
    <xs:attribute type="xs:string" name="isValue" use="optional"/>
    <xs:attribute type="xs:string" name="isNotValue" use="optional"/>
    <xs:attribute type="xs:string" name="applicabilityRef" use="optional"/>
    <xs:attribute type="xs:string" name="pointer" use="optional"/>
  </xs:complexType>
  <xs:complexType name="LambdaType">
    <xs:sequence>
      <xs:element type="ParamType" name="Param" maxOccurs="unbounded" minOccurs="0"/>
      <xs:element type="FunctionType" name="Function" minOccurs="0" maxOccurs="unbounded"/>
    </xs:sequence>
    <xs:attribute type="xs:string" name="name" use="optional"/>
    <xs:attribute type="xs:string" name="object" use="optional"/>
    <xs:attribute type="xs:string" name="matches" use="optional"/>
    <xs:attribute type="xs:string" name="whenProperty" use="optional"/>
    <xs:attribute type="xs:string" name="isValue" use="optional"/>
    <xs:attribute type="xs:string" name="isNotValue" use="optional"/>
    <xs:attribute type="xs:string" name="applicabilityRef" use="optional"/>
  </xs:complexType>
  <xs:complexType name="SetupFunctionsType">
    <xs:choice maxOccurs="unbounded" minOccurs="0">
      <xs:element type="FunctionType" name="Function" maxOccurs="unbounded" minOccurs="0"/>
      <xs:element type="LambdaType" name="Lambda"/>
    </xs:choice>
  </xs:complexType>
  <xs:complexType name="TcMenuPluginType">
    <xs:sequence>
      <xs:element type="SupportedPlatformsType" name="SupportedPlatforms"/>
      <xs:element type="xs:string" name="Description"/>
      <xs:element type="DocumentationType" name="Documentation"/>
      <xs:element type="RequiredLibrariesType" name="RequiredLibraries"/>
      <xs:element type="xs:string" name="ImageFile"/>
      <xs:element type="PropertiesType" name="Properties"/>
      <xs:element type="ApplicabilityDefsType" name="ApplicabilityDefs"/>
      <xs:element type="SourceFilesType" name="SourceFiles"/>
      <xs:element type="IncludeFilesType" name="IncludeFiles"/>
      <xs:element type="GlobalVariablesType" name="GlobalVariables"/>
      <xs:element type="SetupFunctionsType" name="SetupFunctions"/>
    </xs:sequence>
    <xs:attribute type="xs:string" name="name"/>
    <xs:attribute type="xs:string" name="id"/>
    <xs:attribute type="xs:string" name="subsystem"/>
  </xs:complexType>
</xs:schema>

=== TcMenu/tcMenu/web-designer/tcmenu-xml-plugins/core-themes/CoolBlueTraditional.xml
<TcMenuPlugin name="DEPRECATED cool blue traditional" id="03c6b25f-db63-402a-8447-a5ce1484c14d"
              subsystem="THEME" requiresDesigner="2.0" needsTheme="color"
              xmlns="https://www.thecoderscorner.com/libraries/tcmenuPluginItem" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
              xsi:schemaLocation="https://www.thecoderscorner.com/libraries/tcmenuPluginItem https://www.thecoderscorner.com/arduino-libraries/libraries/tcmenu-plugin-item.xsd">
    <SupportedPlatforms>
       <All/>
    </SupportedPlatforms>
    <Description>THIS THEME IS DEPRECATED (kept for existing users), cool blue traditional theme</Description>
    <Documentation link="https://www.thecoderscorner.com/products/arduino-libraries/tc-menu/themes/color-themes-for-all-display-sizes/"/>
    <RequiredLibraries/>
    <ImageFile>theme-cool-blue-traditional.jpg</ImageFile>

    <Properties>
        <Property id="ITEM_FONT" name="%theme.item.font" initial="def:,1" desc="%theme.item.font.desc" type="font"/>
        <Property id="TITLE_FONT" name="%theme.title.font" initial="def:,1" desc="%theme.title.font.desc" type="font"/>
        <Property id="BORDER_FOR_ACTIONS" name="%theme.border.for.action" initial="0" desc="%theme.border.for.action.desc" type="int" min="0" max="3"/>
        <Property id="TITLE_SHOW_MODE" name="%theme.title.show.mode" initial="TITLE_FIRST_ROW" desc="%theme.title.show.mode.desc" type="choice">
            <Choices>
                <Choice desc="%theme.title.none">NO_TITLE</Choice>
                <Choice desc="%theme.title.first.row">TITLE_FIRST_ROW</Choice>
                <Choice desc="%theme.title.always">TITLE_ALWAYS</Choice>
            </Choices>
        </Property>
        <Property id="USE_TC_UNICODE" name="%theme.use.tcunicode" initial="false" type="boolean" desc="%theme.use.tcunicode.desc"/>
        <Property id="USE_SLIDER_ANALOG" name="%theme.use.sliders" initial="true" desc="%theme.use.sliders.desc" type="boolean"/>
        <Property id="NEED_EDITING_ICONS" name="%theme.need.edit.icons" initial="true" desc="theme.need.edit.icons.desc" type="boolean"/>
    </Properties>

    <ApplicabilityDefs/>

    <SourceFiles>
        <SourceFile name="coolBlue/ThemeCoolBlueTraditional.h" overwrite="false"/>
    </SourceFiles>

    <IncludeFiles>
        <Header name="${SRC_DIR_OFFSET}ThemeCoolBlueTraditional.h" inSource="cppSrc"/>
        <Header name="tcUnicodeHelper.h" inSource="false" priority="high" whenProperty="USE_TC_UNICODE" isValue="true" />
        <Header name="${ITEM_FONT}" inSource="font"/>
        <Header name="${TITLE_FONT}" inSource="font"/>
    </IncludeFiles>

    <GlobalVariables>
        <Variable name="${ITEM_FONT}" export="font" whenProperty="ITEM_FONT" matches="ad[al]:.*" />
        <Variable name="${TITLE_FONT}" export="font" whenProperty="ITEM_FONT" matches="ad[al]:.*" />
    </GlobalVariables>

    <SetupFunctions>
        <Function name="setTitleMode" object="renderer">
            <Param name="BaseGraphicalRenderer::${TITLE_SHOW_MODE}"/>
        </Function>

        <Function name="setUseSliderForAnalog" object="renderer">
            <Param name="${USE_SLIDER_ANALOG}"/>
        </Function>

        <Function name="enableTcUnicode" object="renderer" whenProperty="USE_TC_UNICODE" isValue="true"/>

        <Function name="installCoolBlueTraditionalTheme">
            <Param value="renderer"/>
            <Param font="${ITEM_FONT}"/>
            <Param font="${TITLE_FONT}"/>
            <Param value="${NEED_EDITING_ICONS}"/>
        </Function>
    </SetupFunctions>
</TcMenuPlugin>

=== TcMenu/tcMenu/web-designer/tcmenu-xml-plugins/core-display/stm32BspFrameBuffer.xml
<TcMenuPlugin name="%ltdc.driver.name"
              id="fc7b8f22-6553-43d6-9968-df4ee2562aaf" subsystem="DISPLAY"
              requiresDesigner="2.0" needsTheme="color[tcUnicode]"
              xmlns="https://www.thecoderscorner.com/libraries/tcmenuPluginItem" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
              xsi:schemaLocation="https://www.thecoderscorner.com/libraries/tcmenuPluginItem https://www.thecoderscorner.com/arduino-libraries/libraries/tcmenu-plugin-item.xsd">
    <SupportedPlatforms>
        <Platform>MBED_RTOS</Platform>
        <Platform>STM32DUINO</Platform>
    </SupportedPlatforms>
    <Description>%ltdc.driver.desc</Description>
    <Documentation link="https://www.thecoderscorner.com/products/arduino-libraries/tc-menu/tcmenu-plugins/mbed-stm32-menu-touch-display/"/>
    <RequiredLibraries/>
    <ImageFile>adagfx-color.jpg</ImageFile>

    <Properties>
        <Property id="DISPLAY_WIDTH" name="%core.display.width" initial="240" desc="%core.display.width.desc" type="int" min="1" max="10000"/>
        <Property id="DISPLAY_HEIGHT" name="%core.display.height" initial="320" desc="%core.display.height.desc" type="int" min="1" max="10000"/>
        <Property id="UPDATES_PER_SEC" name="%core.screen.updates.sec" initial="10" desc="%core.screen.updates.sec.desc" type="int" min="1" max="10"/>

        <Property id="TOUCH_SEPARATOR" name="%core.touch.separator" initial="" desc="%core.touch.separator.desc" type="separator"/>
        <Property id="TOUCH_SCREEN_REQUIRED" name="%core.touch.required" initial="true" desc="%core.touch.required.desc" type="boolean" />

        <Property id="ORIENTATION_SEPARATOR" name="%core.touch.orientation" initial="" desc="%core.touch.orientation.desc" type="separator"/>
        <Property id="TFT_TOUCH_SWAP_XY" name="%core.touch.swap.xy" initial="false" whenProperty="TOUCH_SCREEN_REQUIRED" isValue="true"
                  desc="%core.touch.swap.xy.desc" type="boolean" />
        <Property id="TFT_TOUCH_X_INVERTED" name="%core.touch.x.inverted" initial="false" whenProperty="TOUCH_SCREEN_REQUIRED" isValue="true"
                  type="boolean" desc="%core.touch.x.inverted.desc"/>
        <Property id="TFT_TOUCH_Y_INVERTED" name="%core.touch.y.inverted" initial="false" whenProperty="TOUCH_SCREEN_REQUIRED" isValue="true"
                  type="boolean" desc="%core.touch.y.inverted.desc"/>

        <Property id="CALIB_SEPARATOR" name="%core.touch.calibration" initial="" desc="%core.touch.calibration.desc" type="separator"/>
        <Property id="TOUCH_SCREEN_CALIBRATE" name="%core.enable.touch.calib" initial="true"
                  desc="%core.enable.touch.calib.desc" type="boolean" whenProperty="TOUCH_SCREEN_REQUIRED" isValue="true"  />
        <Property id="TOUCH_CALIBRATION_STORAGE_LOC" name="%core.touch.calib.addr" initial="400" type="int"
                  desc="%core.touch.calib.addr.desc"  min="4" max="65535" whenProperty="TOUCH_SCREEN_REQUIRED" isValue="true" />
    </Properties>

    <ApplicabilityDefs>
        <ApplicabilityDef key="touchCalibrationNeeded" mode="and">
            <Applicability whenProperty="TOUCH_SCREEN_REQUIRED" isValue="true"/>
            <Applicability whenProperty="TOUCH_SCREEN_CALIBRATE" isValue="true"/>
        </ApplicabilityDef>
    </ApplicabilityDefs>
    <SourceFiles>
        <Replacement find="define TC_BSP_TOUCH_DEVICE_PRESENT true" replace="define TC_BSP_TOUCH_DEVICE_PRESENT ${TOUCH_SCREEN_REQUIRED}"/>
        <Replacement find="BspUserSettings\\.h" replace="${SRC_DIR_OFFSET}BspUserSettings.h"/>
        <SourceFile name="mbedStm32Bsp/BspUserSettings.h" overwrite="false"/>
        <SourceFile name="mbedStm32Bsp/tcMenuStChromaArt.h" />
        <SourceFile name="mbedStm32Bsp/tcMenuStChromaArt.cpp" />
    </SourceFiles>

    <IncludeFiles>
        <Header name="${SRC_DIR_OFFSET}BspUserSettings.h" inSource="true"/>
        <Header name="tcMenuStChromaArt.h" inSource="true"/>
        <Header name="graphics/MenuTouchScreenEncoder.h" inSource="false"/>
        <Header name="extras/DrawableTouchCalibrator.h" inSource="false" applicabilityRef="touchCalibrationNeeded"/>
    </IncludeFiles>

    <GlobalVariables>
        <Variable name="${DISPLAY_VARIABLE}Drawable" type="StChromaArtDrawable" export="true"/>

        <Variable name="renderer" type="GraphicsDeviceRenderer" export="true">
            <Param value="30"/>
            <Param value="applicationInfo.name"/>
            <Param ref="${DISPLAY_VARIABLE}Drawable"/>
        </Variable>

        <Variable name="touchInterrogator" type="StBspTouchInterrogator" export="true" whenProperty="TOUCH_SCREEN_REQUIRED" isValue="true">
            <Param value="${DISPLAY_WIDTH}"/>
            <Param value="${DISPLAY_HEIGHT}"/>
        </Variable>

        <Variable name="touchOrientation" type="iotouch::TouchOrientationSettings" export="false" whenProperty="TOUCH_SCREEN_REQUIRED" isValue="true">
            <Param value="${TFT_TOUCH_SWAP_XY}"/>
            <Param value="${TFT_TOUCH_X_INVERTED}"/>
            <Param value="${TFT_TOUCH_Y_INVERTED}"/>
        </Variable>

        <Variable name="touchScreen" type="MenuTouchScreenManager" export="true" whenProperty="TOUCH_SCREEN_REQUIRED" isValue="true">
            <Param ref="touchInterrogator"/>
            <Param ref="renderer"/>
            <Param value="touchOrientation"/>
        </Variable>

        <Variable name="touchCalibrator" type="tcextras::IoaTouchScreenCalibrator" export="true" applicabilityRef="touchCalibrationNeeded">
            <Param ref="touchScreen"/>
            <Param ref="renderer"/>
            <Param value="${TOUCH_CALIBRATION_STORAGE_LOC}"/>
        </Variable>

    </GlobalVariables>

    <SetupFunctions>
        <Function object="renderer" name="setUpdatesPerSecond">
            <Param value="${UPDATES_PER_SEC}"/>
        </Function>

        <Function name="start" object="touchScreen" whenProperty="TOUCH_SCREEN_REQUIRED" isValue="true"/>
    </SetupFunctions>
</TcMenuPlugin>

=== TcMenu/tcMenu/web-designer/tcmenu-xml-plugins/core-themes/MonoInverseTitleBuilder.xml
<TcMenuPlugin name="%theme.mono.inverse.name" id="396ED4DF-AD7B-4951-A848-A9E5838A549B"
              subsystem="THEME" requiresDesigner="2.0" needsTheme="mono"
              xmlns="https://www.thecoderscorner.com/libraries/tcmenuPluginItem" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
              xsi:schemaLocation="https://www.thecoderscorner.com/libraries/tcmenuPluginItem https://www.thecoderscorner.com/arduino-libraries/libraries/tcmenu-plugin-item.xsd">
    <SupportedPlatforms>
       <All/>
    </SupportedPlatforms>
    <Description>%theme.mono.inverse.desc</Description>
    <Documentation link="https://www.thecoderscorner.com/products/arduino-libraries//tc-menu/themes/monochrome-themes-for-oled-5110/"/>
    <RequiredLibraries/>
    <ImageFile>theme-oled-inverse.jpg</ImageFile>

    <Properties>
        <Property id="ITEM_FONT" name="%theme.item.font" initial="def:,1" desc="%theme.item.font.desc" type="font"/>
        <Property id="TITLE_FONT" name="%theme.title.font" initial="def:,1" desc="%theme.title.font.desc" type="font"/>
        <Property id="TITLE_HEADER_PADDING" name="%theme.item.header.padding" initial="2" desc="%theme.item.header.padding.desc" type="int" min="0" max="10"/>
        <Property id="TITLE_TO_ITEM_SPACING" name="%theme.mono.spacing.title.item" initial="2" desc="The spacing between the title and the first item" type="int" min="0" max="10"/>
        <Property id="TITLE_SHOW_MODE" name="%theme.title.show.mode" initial="TITLE_FIRST_ROW" desc="%theme.title.show.mode.desc" type="choice">
            <Choices>
                <Choice desc="%theme.title.none">NO_TITLE</Choice>
                <Choice desc="%theme.title.first.row">TITLE_FIRST_ROW</Choice>
                <Choice desc="%theme.title.always">TITLE_ALWAYS</Choice>
            </Choices>
        </Property>
        <Property id="USE_TC_UNICODE" name="%theme.use.tcunicode" initial="false" type="boolean" desc="%theme.use.tcunicode.desc"/>
    </Properties>

    <ApplicabilityDefs/>

    <SourceFiles>
        <Replacement find="TITLE_SPACING 1" replace="TITLE_SPACING ${TITLE_TO_ITEM_SPACING}"/>
        <Replacement find="TITLE_PADDING 1" replace="TITLE_PADDING ${TITLE_HEADER_PADDING}"/>
        <SourceFile name="monoThemes/ThemeMonoInverseBuilder.h" overwrite="false"/>
    </SourceFiles>

    <IncludeFiles>
        <Header name="${SRC_DIR_OFFSET}ThemeMonoInverseBuilder.h" inSource="cppSrc"/>
        <Header name="tcUnicodeHelper.h" inSource="false" priority="high" whenProperty="USE_TC_UNICODE" isValue="true" />
        <Header name="${ITEM_FONT}" inSource="font"/>
        <Header name="${TITLE_FONT}" inSource="font"/>
    </IncludeFiles>

    <GlobalVariables>
        <Variable name="${ITEM_FONT}" export="font" whenProperty="ITEM_FONT" matches="ad[al]:.*" />
        <Variable name="${TITLE_FONT}" export="font" whenProperty="ITEM_FONT" matches="ad[al]:.*" />
    </GlobalVariables>

    <SetupFunctions>
        <Function name="installMonoInverseTitleTheme">
            <Param value="renderer"/>
            <Param font="${ITEM_FONT}"/>
            <Param font="${TITLE_FONT}"/>
            <Param value="true"/>
            <Param name="BaseGraphicalRenderer::${TITLE_SHOW_MODE}"/>
            <Param name="${USE_TC_UNICODE}"/>
        </Function>
    </SetupFunctions>
</TcMenuPlugin>

=== TcMenu/tcMenu/CoreXmlPlugins/core-remote/remoteEthernet.xml
<TcMenuPlugin name="Ethernet control of your menu using popular libraries" id="0877131c-e03e-426b-8eaf-228e01f5e7f1" subsystem="REMOTE"
              xmlns="https://www.thecoderscorner.com/libraries/tcmenuPluginItem" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
              xsi:schemaLocation="https://www.thecoderscorner.com/libraries/tcmenuPluginItem https://www.thecoderscorner.com/libraries/tcmenu-plugin-item.xsd">
    <SupportedPlatforms>
        <Platform>ARDUINO_UNO</Platform>
        <Platform>ARDUINO_AVR</Platform>
        <Platform>ARDUINO_32</Platform>
        <Platform>ARDUINO_ESP8266</Platform>
        <Platform>ARDUINO_ESP32</Platform>
    </SupportedPlatforms>
    <Description>Use this option to be able to control the menu over many kinds of ethernet shields and devices. The full menu structure will be available to the remote using either the protocol or the API.</Description>
    <Documentation link="https://www.thecoderscorner.com/products/arduino-libraries/tc-menu/tcmenu-plugins/ethernet-remote-plugin/"/>
    <RequiredLibraries/>
    <ImageFile>ethernet-shield.jpg</ImageFile>

    <Properties>
        <Property id="LIBRARY_TYPE" name="Ethernet library type" desc="Choose the library that supports your hardware" initial="ETHERNET_2" type="choice">
            <Choices>
                <Choice>ETHERNET_2</Choice>
                <Choice>UIP_ENC28J60</Choice>
            </Choices>
        </Property>
        <Property id="LISTEN_PORT" name="Port on which to listen" initial="3333" desc="The port on which to listen" type="int" min="0" max="65355"/>
    </Properties>

    <ApplicabilityDefs/>

    <SourceFiles>
        <Replacement find="Ethernet.h" replace="UIPEthernet.h" whenProperty="LIBRARY_TYPE" isValue="UIP_ENC28J60"/>
        <Replacement find="EthernetClient" replace="UIPClient" whenProperty="LIBRARY_TYPE" isValue="UIP_ENC28J60"/>
        <Replacement find="EthernetServer" replace="UIPServer" whenProperty="LIBRARY_TYPE" isValue="UIP_ENC28J60"/>
        <Replacement find="ETHERNET_BUFFER_SIZE 0" replace="ETHERNET_BUFFER_SIZE 64" whenProperty="LIBRARY_TYPE" isValue="ETHERNET_2"/>

        <SourceFile name="ethernetSrc/EthernetTransport.cpp"/>
        <SourceFile name="ethernetSrc/EthernetTransport.h"/>
    </SourceFiles>

    <IncludeFiles>
        <Header name="EthernetTransport.h" inSource="true"/>
        <Header name="RemoteConnector.h" inSource="false"/>
    </IncludeFiles>

    <GlobalVariables>
        <Variable name="server" type="EthernetServer" export="true">
            <Param value="${LISTEN_PORT}" default="3333" />
        </Variable>
    </GlobalVariables>

    <SetupFunctions>
        <Function name="begin" object="remoteServer">
            <Param ref="server"/>
            <Param ref="applicationInfo"/>
        </Function>
    </SetupFunctions>
</TcMenuPlugin>
